export const basicHelps = {
  cn: {
    wild: "百搭",
    freegame: "免费游戏",
    symbolBouns: "分散图奖",
  },
  en: {
    wild: "WILD",
    freegame: "FREE GAME",
    symbolBouns: "SCATTER",
  },
  th: {
    wild: "ไวลด์",
    freegame: "เกมฟรี",
    symbolBouns: "สแคตเตอร์",
  },
  id: {
    wild: "WILD",
    freegame: "FREE GAME",
    symbolBouns: "SCATTER",
  },
  vn: {
    wild: "WILD",
    freegame: "FREE GAME",
    symbolBouns: "SCATTER",
  },
  ko: {
    wild: "WILD",
    freegame: "FREE GAME",
    symbolBouns: "SCATTER",
  },
  es: {
    wild: "COMODÍN",
    freegame: "JUEGO GRATIS",
    symbolBouns: "DISPERSIÓN",
  },
  ja: {
    wild: "ワイルド",
    freegame: "フリーゲーム",
    symbolBouns: "分散絵柄",
  },
  "pt-BR": {
    wild: "SELVAGEM",
    freegame: "JOGO GRÁTIS",
    symbolBouns: "DESORDEM",
  },
  ph: {
    wild: "WILD",
    freegame: "FREE GAME",
    symbolBouns: "NAKAKALAT",
  },
};
export const slotHelpInitData = (lang = "cn") => {
  return [
    {
      title: basicHelps[lang].wild,
      content: "",
      icon: {
        name: "百搭",
        link: "W",
      },
    },
    {
      title: basicHelps[lang].freegame,
      titleType2: basicHelps[lang].symbolBouns,
      content: "",
      icon: {
        name: "免費遊戲 / 分散图奖",
        link: "F",
      },
    },
    // {
    //   title: basicHelps[lang].updateRule,
    //   content: "",
    // },
  ];
};
export const slotIconsLink = [
  { title: "無", key: "none" },
  {
    title: "百搭",
    key: "W",
  },
  {
    title: "特例百搭",
    key: "W_S",
  },
  {
    title: "免費遊戲 / 分散奖图",
    key: "F",
  },
  {
    title: "免費遊戲特色",
    key: "free_game_feature",
  },
  {
    title: "(多國)免費遊戲特色",
    key: "free_game_feature",
  },
  {
    title: "主遊戲特色",
    key: "main_game_feature",
  },
  {
    title: "(多國)主遊戲特色",
    key: "main_game_feature",
  },
  {
    title: "再旋轉特色",
    key: "resin_feature",
  },
  {
    title: "(多國)再旋轉特色",
    key: "resin_feature",
  },
  {
    title: "超級百搭",
    key: "super_wild",
  },
  {
    title: "隨機百搭",
    key: "random_wild",
  },
  {
    title: "彩金",
    key: "JP",
  },
];
export const slotGameQuickBlocks = {
  cn: [
    {
      title: "免费游戏特色",
      value: "免费游戏特色",
    },
    {
      title: "主游戏特色",
      value: "主游戏特色",
    },
    {
      title: "奖励游戏特色",
      value: "奖励游戏特色",
    },
    {
      title: "再旋转特色",
      value: "再旋转特色",
    },
    {
      title: "共同游戏特色",
      value: "共同游戏特色",
    },
    {
      title: "百搭延展特色",
      value: "百搭延展特色",
    },
    {
      title: "购买特色",
      value: "购买特色",
    },
    {
      title: "升級規則",
      value: "升級規則",
      key: "updateRule",
    },
    {
      title: "再获奖规则",
      value: "再获奖规则",
    },
  ],
  en: [
    {
      title: "免费游戏特色",
      value: "FREE GAME FEATURE",
    },
    {
      title: "主游戏特色",
      value: "BASE GAMES",
    },
    {
      title: "奖励游戏特色",
      value: "BONUS GAME FEATURE",
    },

    {
      title: "再旋转特色",
      value: "RESPIN FEATURE",
    },
    {
      title: "共同游戏特色",
      value: "COMMON FEATURE",
    },
    {
      title: "百搭延展特色",
      value: "Expanding Wild Feature",
    },
    {
      title: "购买特色",
      value: "BUY FEATURE",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "RETRIGGER",
      key: "updateRule",
    },
  ],
  th: [
    {
      title: "免费游戏特色",
      value: "ฟีเจอร์เกมฟรี",
    },
    {
      title: "主游戏特色",
      value: "เกมหลัก",
    },
    {
      title: "奖励游戏特色",
      value: "ฟีเจอร์เกมโบนัส",
    },

    {
      title: "再旋转特色",
      value: "ฟีเจอร์รีสปิน",
    },
    {
      title: "共同游戏特色",
      value: "ฟีเจอร์",
    },
    {
      title: "百搭延展特色",
      value: "ขยายฟีเจอร์ไวลด์",
    },
    {
      title: "购买特色",
      value: "ซื้อฟีเจอร์",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "กฎรีทริกเกอร์",
      key: "updateRule",
    },
  ],
  id: [
    {
      title: "免费游戏特色",
      value: "FREE GAME FEATURE",
    },
    {
      title: "主游戏特色",
      value: "BASE GAMES",
    },
    {
      title: "奖励游戏特色",
      value: "BONUS GAME FEATURE",
    },

    {
      title: "再旋转特色",
      value: "RESPIN FEATURE",
    },
    {
      title: "共同游戏特色",
      value: "FEATURE",
    },
    {
      title: "百搭延展特色",
      value: "Fitur Wild Meluas",
    },
    {
      title: "购买特色",
      value: "Fitur pembelian",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "RETRIGGER",
      key: "updateRule",
    },
  ],
  vn: [
    {
      title: "免费游戏特色",
      value: "FREE GAME FEATURE",
    },
    {
      title: "主游戏特色",
      value: "BASE GAMES",
    },
    {
      title: "奖励游戏特色",
      value: "BONUS GAME FEATURE",
    },

    {
      title: "再旋转特色",
      value: "RESPIN FEATURE",
    },
    {
      title: "共同游戏特色",
      value: "FEATURE",
    },
    {
      title: "百搭延展特色",
      value: "Mở rộng tính năng biểu tượng vạn năng",
    },
    {
      title: "购买特色",
      value: "Mua tính năng",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "RETRIGGER",
      key: "updateRule",
    },
  ],
  ko: [
    {
      title: "免费游戏特色",
      value: "FREE GAME FEATURE",
    },
    {
      title: "主游戏特色",
      value: "BASE GAMES",
    },
    {
      title: "奖励游戏特色",
      value: "BONUS GAME FEATURE",
    },

    {
      title: "再旋转特色",
      value: "RESPIN FEATURE",
    },
    {
      title: "共同游戏特色",
      value: "FEATURE",
    },
    {
      title: "百搭延展特色",
      value: "와일드 피처 확장",
    },
    {
      title: "购买特色",
      value: "구매 기능",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "RETRIGGER",
      key: "updateRule",
    },
  ],
  es: [
    {
      title: "免费游戏特色",
      value: "CARACTERÍSTICA DE JUEGO GRATIS",
    },
    {
      title: "主游戏特色",
      value: "JUEGO DE BASE",
    },
    {
      title: "奖励游戏特色",
      value: "CARACTERÍSTICA DE JUEGO DE BONIFICACIÓN",
    },

    {
      title: "再旋转特色",
      value: "CARACTERÍSTICA DE NUEVO GIRO",
    },
    {
      title: "共同游戏特色",
      value: "CARACTERÍSTICA",
    },
    {
      title: "百搭延展特色",
      value: "Característica de Comodín Expandible",
    },
    {
      title: "购买特色",
      value: "Comprar Característica",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "REGLAS DE REACTIVACIÓN",
      key: "updateRule",
    },
  ],
  ja: [
    {
      title: "免费游戏特色",
      value: "フリーゲームの特徴",
    },
    {
      title: "主游戏特色",
      value: "ベースゲーム",
    },
    {
      title: "奖励游戏特色",
      value: "ボーナスゲームの特色",
    },
    {
      title: "再旋转特色",
      value: "リスピンの特徴",
    },
    {
      title: "共同游戏特色",
      value: "特徴",
    },
    {
      title: "百搭延展特色",
      value: "拡張ワイルド機能",
    },
    {
      title: "购买特色",
      value: "フリースピン購入",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "再トリガルール",
      key: "updateRule",
    },
  ],
  "pt-BR": [
    {
      title: "免费游戏特色",
      value: "FUNÇÃO DE JOGO GRÁTIS",
    },
    {
      title: "主游戏特色",
      value: "JOGO BASE",
    },
    {
      title: "奖励游戏特色",
      value: "CARACTERÍSTICA DO JOGO BÔNUS",
    },
    {
      title: "再旋转特色",
      value: "FUNÇÃO DE GIRO EXTRA",
    },
    {
      title: "共同游戏特色",
      value: "FUNÇÃO",
    },
    {
      title: "百搭延展特色",
      value: "Expandindo o recurso louco",
    },
    {
      title: "购买特色",
      value: "COMPRAR RECURSO",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "REGRAS DE REATIVAÇÃO",
      key: "updateRule",
    },
  ],
  ph: [
    {
      title: "免费游戏特色",
      value: "FREE GAME FEATURE",
    },
    {
      title: "主游戏特色",
      value: "Normal na laro",
    },
    {
      title: "奖励游戏特色",
      value: "BONUS GAME FEATURE",
    },
    {
      title: "再旋转特色",
      value: "RESPIN FEATURE",
    },
    {
      title: "共同游戏特色",
      value: "Pangunahing Patakaran",
    },
    {
      title: "百搭延展特色",
      value: "Expanding Wild Feature",
    },
    {
      title: "购买特色",
      value: "BUY FEATURE",
    },
    {
      title: "升級規則 / 再获奖规则",
      value: "RETRIGGER",
      key: "updateRule",
    },
  ],
};
export const slotGameLine = [
  {
    type: "none",
    name: {
      cn: "無",
      en: "none",
      th: "none",
      id: "none",
      vn: "none",
      ko: "none",
      es: "none",
      ja: "none",
      "pt-BR": "none",
      ph: "none",
    },
    content: {
      cn: "",
      en: "",
      th: "",
      id: "",
      vn: "",
      ko: "",
      es: "",
      ja: "",
      "pt-BR": "",
      ph: "",
    },
  },
  {
    type: "108",
    name: {
      cn: "108路",
      en: "108 WAYS",
      th: "108 WAYS",
      id: "108 WAYS",
      vn: "108 WAYS",
      ko: "108 WAYS",
      es: "108 FORMAS",
      ja: "108 通り",
      "pt-BR": "108 CAMINHOS",
      ph: "108 WAYS",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现 <span style='color:#ffff1a'>3</span> 个以上相同图标，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>3</span> ตัวหรือมากกว่าปรากฎบนวงล้อต่อเนื่องจากซ้ายไปขวา.</p>",
      id: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      vn: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 <span style='color:#ffff1a'>3</span> 번 이상 나타나면 상품을 획득합니다.</p>",
      es: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ja: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      "pt-BR":
        "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ph: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
    },
  },
  {
    type: "243",
    name: {
      cn: "243路",
      en: "243 WAYS",
      th: "243 WAYS",
      id: "243 WAYS",
      vn: "243 WAYS",
      ko: "243 WAYS",
      es: "243 FORMAS",
      ja: "243 通り",
      "pt-BR": "243 CAMINHOS",
      ph: "243 WAYS",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现 <span style='color:#ffff1a'>3</span> 个以上相同图标，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>3</span> ตัวหรือมากกว่าปรากฎบนวงล้อต่อเนื่องจากซ้ายไปขวา.</p>",
      id: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      vn: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 <span style='color:#ffff1a'>3</span> 번 이상 나타나면 상품을 획득합니다.</p>",
      es: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ja: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      "pt-BR":
        "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ph: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
    },
  },
  {
    type: "576",
    name: {
      cn: "576路",
      en: "576 WAYS",
      th: "576 WAYS",
      id: "576 WAYS",
      vn: "576 WAYS",
      ko: "576 WAYS",
      es: "576 FORMAS",
      ja: "576 通り",
      "pt-BR": "576 CAMINHOS",
      ph: "576 WAYS",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现 <span style='color:#ffff1a'>3</span> 个以上相同图标，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>3</span> ตัวหรือมากกว่าปรากฎบนวงล้อต่อเนื่องจากซ้ายไปขวา.</p>",
      id: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      vn: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 <span style='color:#ffff1a'>3</span> 번 이상 나타나면 상품을 획득합니다.</p>",
      es: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ja: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      "pt-BR":
        "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ph: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
    },
  },
  {
    type: "1024",
    name: {
      cn: "1024路",
      en: "1024 WAYS",
      th: "1024 WAYS",
      id: "1024 WAYS",
      vn: "1024 WAYS",
      ko: "1024 WAYS",
      es: "1024 FORMAS",
      ja: "1024 通り",
      "pt-BR": "1024 CAMINHOS",
      ph: "1024 WAYS",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现 <span style='color:#ffff1a'>3</span> 个以上相同图标，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>3</span> ตัวหรือมากกว่าปรากฎบนวงล้อต่อเนื่องจากซ้ายไปขวา.</p>",
      id: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      vn: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 <span style='color:#ffff1a'>3</span> 번 이상 나타나면 상품을 획득합니다.</p>",
      es: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ja: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      "pt-BR":
        "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ph: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the continuous reels from leftmost to right.</p>",
    },
  },
  {
    type: "1",
    name: {
      cn: "1线",
      en: "1 LINE",
      th: "1 LINE",
      id: "1 LINE",
      vn: "1 đường",
      ko: "1 LINE",
      es: "1 LÍNEA",
      ja: "1 ライン",
      "pt-BR": "1 LINHA",
      ph: "1 LINE",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续 <span style='color:#ffff1a'>3</span> 个相同图标出现在押注线上，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> the same symbols appearing on the lines from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>3</span> ตัว ปรากฎบนแนวเส้นจากซ้ายสุดไปทางขวา</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat <span style='color:#ffff1a'>3</span> simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p>",
      vn: "<p>Người chơi sẽ giành giải thưởng khi có bất kỳ <span style='color:#ffff1a'>3</span> hình giống nhau nào xuất hiện trên các hàng từ sát bên trái sang phải.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 <span style='color:#ffff1a'>3</span>개 나타나면 상품을 획득합니다.</p>",
      es: "<p>El jugador ganará la bonificación con <span style='color:#ffff1a'>3</span> o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p>",
      ja: "<p>左端から右へ、ライン上に <span style='color:#ffff1a'>3</span> つ同じシンボルで賞品が獲得できます。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com quaisquer <span style='color:#ffff1a'>3</span> símbolos iguais que aparecem nas linhas da esquerda para a direita.</p>",
      ph: "<p></p>",
    },
  },
  {
    type: "5",
    name: {
      cn: "5线",
      en: "5 LINES",
      th: "5 LINES",
      id: "5 LINES",
      vn: "5 đường",
      ko: "5 LINES",
      es: "5 LÍNEAS",
      ja: "5 ライン",
      "pt-BR": "5 LINHAS",
      ph: "5 LINES",
    },
    content: {
      cn: "<p>免费游戏无法再次获奖。</p><p>免费游戏最多场次为8场。</p><p>免费游戏中，押注倍数与触发免费游戏奖励时相同。</p><p>滚轮上由最左至右连续3个相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any 3 the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมี 3 สัญลักษณ์เหมือนกันปรากฎบนเส้น จากซ้ายไปขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกันสูงสุดเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ giành giải thưởng với một trong 3 hình giống nhau xuất hiện trên các hàng từ phía ngoài cùng bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3개 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>左端から右へ、ライン上に3つ同じシンボルで賞品が獲得できます。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Somente a vitória mais alta paga por combinação vencedora.</p>",
      ph: "<p>Player will win prize with any 3 the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
    },
  },
  {
    type: "9",
    name: {
      cn: "9线",
      en: "9 LINES",
      th: "9 LINES",
      id: "9 LINES",
      vn: "9 đường",
      ko: "9 LINES",
      es: "9 LÍNEAS",
      ja: "9 ライン",
      "pt-BR": "9 LINHAS",
      ph: "9 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续<span style='color:#ffff1a'>2</span>或<span style='color:#ffff1a'>3</span>个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>2</span> or <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>2</span> หรือ <span style='color:#ffff1a'>3</span> หรือ ตัวหรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไปทางขวา</p><p>จ่ายเฉพาะรางวัลที่ชนะสูงสุดต่อครั้งเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat <span style='color:#ffff1a'>2</span> atau <span style='color:#ffff1a'>3</span> atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng khi có bất kỳ <span style='color:#ffff1a'>2</span> hoặc <span style='color:#ffff1a'>3</span> hoặc là hình giống nhau nào trở lên xuất hiện trên các hàng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 <span style='color:#ffff1a'>2</span>~<span style='color:#ffff1a'>3</span>번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して<span style='color:#ffff1a'>2</span>個または<span style='color:#ffff1a'>3</span>個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com <span style='color:#ffff1a'>2</span> ou <span style='color:#ffff1a'>3</span> ou mais símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ph: "<p>Ang manlalaro ay mananalo ng premyo sa alinmang <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o higit pang magkakaparehong simbolo na lumalabas sa mga linya mula sa pinakakaliwa hanggang kanan.</p><p>Tanging ang pinakamataas na panalo ang babayaran sa bawat panalong kombinasyon.</p>",
    },
  },
  {
    type: "9_2",
    name: {
      cn: "9线(2)",
      en: "9 LINES(2)",
      th: "9 LINES(2)",
      id: "9 LINES(2)",
      vn: "9 đường(2)",
      ko: "9 LINES(2)",
      es: "9 LÍNEAS(2)",
      ja: "9 ライン(2)",
      "pt-BR": "9 LINHAS(2)",
      ph: "9 LINES(2)",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续<span style='color:#ffff1a'>2</span>或<span style='color:#ffff1a'>3</span>个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>2</span> or <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>2</span> หรือ <span style='color:#ffff1a'>3</span> หรือ ตัวหรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไปทางขวา</p><p>จ่ายเฉพาะรางวัลที่ชนะสูงสุดต่อครั้งเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat <span style='color:#ffff1a'>2</span> atau <span style='color:#ffff1a'>3</span> atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng khi có bất kỳ <span style='color:#ffff1a'>2</span> hoặc <span style='color:#ffff1a'>3</span> hoặc là hình giống nhau nào trở lên xuất hiện trên các hàng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 <span style='color:#ffff1a'>2</span>~<span style='color:#ffff1a'>3</span>번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して<span style='color:#ffff1a'>2</span>個または<span style='color:#ffff1a'>3</span>個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com <span style='color:#ffff1a'>2</span> ou <span style='color:#ffff1a'>3</span> ou mais símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ph: "<p>Ang manlalaro ay mananalo ng premyo sa alinmang <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o higit pang magkakaparehong simbolo na lumalabas sa mga linya mula sa pinakakaliwa hanggang kanan.</p><p>Tanging ang pinakamataas na panalo ang babayaran sa bawat panalong kombinasyon.</p>",
    },
  },
  {
    type: "10",
    name: {
      cn: "10线",
      en: "10 LINES",
      th: "10 LINES",
      id: "10 LINES",
      vn: "10 đường",
      ko: "10 LINES",
      es: "10 LÍNEAS",
      ja: "10 ライン",
      "pt-BR": "10 LINHAS",
      ph: "10 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续<span style='color:#ffff1a'>2</span>或<span style='color:#ffff1a'>3</span>个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>2</span> or <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>2</span> หรือ <span style='color:#ffff1a'>3</span> หรือ ตัวหรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไปทางขวา</p><p>จ่ายเฉพาะรางวัลที่ชนะสูงสุดต่อครั้งเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat <span style='color:#ffff1a'>2</span> atau <span style='color:#ffff1a'>3</span> atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng khi có bất kỳ <span style='color:#ffff1a'>2</span> hoặc <span style='color:#ffff1a'>3</span> hoặc là hình giống nhau nào trở lên xuất hiện trên các hàng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 <span style='color:#ffff1a'>2</span>~<span style='color:#ffff1a'>3</span>번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して<span style='color:#ffff1a'>2</span>個または<span style='color:#ffff1a'>3</span>個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com <span style='color:#ffff1a'>2</span> ou <span style='color:#ffff1a'>3</span> ou mais símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ph: "<p>Ang manlalaro ay mananalo ng premyo sa alinmang <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o higit pang magkakaparehong simbolo na lumalabas sa mga linya mula sa pinakakaliwa hanggang kanan.</p><p>Tanging ang pinakamataas na panalo ang babayaran sa bawat panalong kombinasyon.</p>",
    },
  },
  {
    type: "15",
    name: {
      cn: "15线",
      en: "15 LINES",
      th: "15 LINES",
      id: "15 LINES",
      vn: "15 đường",
      ko: "15 LINES",
      es: "15 LÍNEAS",
      ja: "15 ライン",
      "pt-BR": "15 LINHAS",
      ph: "15 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现3个以上的相同图标，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p><p>Malfunction Voids All Pays and Play.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและ การเล่นทั้งหมดเป็นโมฆะ</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>",
      ph: "<p>Ang manlalaro ay mananalo ng premyo sa alinmang 3 o higit pang magkakaparehong icon na lumalabas sa mga linya mula sa pinakakaliwa hanggang kanan.</p><p>Somente a vitória mais alta paga por combinação vencedora.</p><p>Ang Hindi Paggana ay Pinapawalang-bisa ang Lahat ng Bayad at Laro.</p>",
    },
  },
  {
    type: "15_2",
    name: {
      cn: "15线(2)",
      en: "15 LINES(2)",
      th: "15 LINES(2)",
      id: "15 LINES(2)",
      vn: "15 đường(2)",
      ko: "15 LINES(2)",
      es: "15 LÍNEAS(2)",
      ja: "15 ライン(2)",
      "pt-BR": "15 LINHAS(2)",
      ph: "15 LINES(2)",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现3个以上的相同图标，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p><p>Malfunction Voids All Pays and Play.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและ การเล่นทั้งหมดเป็นโมฆะ</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>",
      ph: "<p>Ang manlalaro ay mananalo ng premyo sa alinmang 3 o higit pang magkakaparehong icon na lumalabas sa mga linya mula sa pinakakaliwa hanggang kanan.</p><p>Somente a vitória mais alta paga por combinação vencedora.</p><p>Ang Hindi Paggana ay Pinapawalang-bisa ang Lahat ng Bayad at Laro.</p>",
    },
  },
  {
    type: "20",
    name: {
      cn: "20线",
      en: "20 LINES",
      th: "20 LINES",
      id: "20 LINES",
      vn: "20 đường",
      ko: "20 LINES",
      es: "20 LÍNEAS",
      ja: "20 ライン",
      "pt-BR": "20 LINHAS",
      ph: "20 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续<span style='color:#ffff1a'>2</span>或<span style='color:#ffff1a'>3</span>个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>2</span> or <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>2</span> หรือ <span style='color:#ffff1a'>3</span> หรือ ตัวหรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไปทางขวา</p><p>จ่ายเฉพาะรางวัลที่ชนะสูงสุดต่อครั้งเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat <span style='color:#ffff1a'>2</span> atau <span style='color:#ffff1a'>3</span> atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng khi có bất kỳ <span style='color:#ffff1a'>2</span> hoặc <span style='color:#ffff1a'>3</span> hoặc là hình giống nhau nào trở lên xuất hiện trên các hàng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 <span style='color:#ffff1a'>2</span>~<span style='color:#ffff1a'>3</span>번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して<span style='color:#ffff1a'>2</span>個または<span style='color:#ffff1a'>3</span>個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com <span style='color:#ffff1a'>2</span> ou <span style='color:#ffff1a'>3</span> ou mais símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ph: "<p>Ang manlalaro ay mananalo ng premyo sa alinmang <span style='color:#ffff1a'>2</span> o <span style='color:#ffff1a'>3</span> o higit pang magkakaparehong simbolo na lumalabas sa mga linya mula sa pinakakaliwa hanggang kanan.</p><p>Tanging ang pinakamataas na panalo ang babayaran sa bawat panalong kombinasyon.</p>",
    },
  },
  {
    type: "20_2",
    name: {
      cn: "20线(2)",
      en: "20 LINES(2)",
      th: "20 LINES(2)",
      id: "20 LINES(2)",
      vn: "20 đường(2)",
      ko: "20 LINES(2)",
      es: "20 LÍNEAS(2)",
      ja: "20 ライン(2)",
      "pt-BR": "20 LINHAS(2)",
      ph: "20 LINES(2)",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续 <span style='color:#ffff1a'>3</span> 个以上相同图标出现在押注线上，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน <span style='color:#ffff1a'>3</span> ตัวหรือมากกว่าปรากฎบนเส้นไลน์เดิมพันต่อเนื่องจากซ้ายไปขวา </p>",
      id: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
      vn: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
      ko: "<p>맨 왼쪽에서 오른쪽으로 같은 부호가 <span style='color:#ffff1a'>3</span>개 이상 베팅 라인에 나타나면, 해당 부호의 득점을 획득할 수 있습니다.</p>",
      es: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
      ja: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
      "pt-BR":
        "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
      ph: "<p>Player will win prize with any <span style='color:#ffff1a'>3</span> or more the same symbols appearing on the lines from leftmost to right.</p>",
    },
  },
  {
    type: "25",
    name: {
      cn: "25线",
      en: "25 LINES",
      th: "25 LINES",
      id: "25 LINES",
      vn: "25 đường",
      ko: "25 LINES",
      es: "25 LÍNEAS",
      ja: "25 ライン",
      "pt-BR": "25 LINHAS",
      ph: "25 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续3个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p>",
      ph: "<p></p><p></p>",
    },
  },
  {
    type: "40",
    name: {
      cn: "40线",
      en: "40 LINES",
      th: "40 LINES",
      id: "40 LINES",
      vn: "40 đường",
      ko: "40 LINES",
      es: "40 LÍNEAS",
      ja: "40 ライン",
      "pt-BR": "40 LINHAS",
      ph: "40 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续3个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p>",
      ph: "<p></p><p></p>",
    },
  },
  {
    type: "50",
    name: {
      cn: "50线",
      en: "50 LINES",
      th: "50 LINES",
      id: "50 LINES",
      vn: "50 đường",
      ko: "50 LINES",
      es: "50 LÍNEAS",
      ja: "50 ライン",
      "pt-BR": "50 LINHAS",
      ph: "50 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续3个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p>",
      ph: "<p></p><p></p>",
    },
  },
  {
    type: "60",
    name: {
      cn: "60线",
      en: "60 LINES",
      th: "60 LINES",
      id: "60 LINES",
      vn: "60 đường",
      ko: "60 LINES",
      es: "60 LÍNEAS",
      ja: "60 ライン",
      "pt-BR": "60 LINHAS",
      ph: "60 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续3个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p><p>Malfunction Voids All Pays and Play.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและการเล่น ทั้งหมดเป็นโมฆะ</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p><p>Si se produce un error de funcionamiento, se anularán todas las jugadas y pagos.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>",
      ph: "<p></p><p></p><p>Ang Hindi Paggana ay Pinapawalang-bisa ang Lahat ng Bayad at Laro.</p>",
    },
  },
  {
    type: "88",
    name: {
      cn: "88线",
      en: "88 LINES",
      th: "88 LINES",
      id: "88 LINES",
      vn: "88 đường",
      ko: "88 LINES",
      es: "88 LÍNEAS",
      ja: "88 ライン",
      "pt-BR": "88 LINHAS",
      ph: "88 LINES",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续3个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the lines from leftmost to right.</p><p>Only highest win paid per winning combination.</p><p>Malfunction Voids All Pays and Play.</p>",
      th: "<p>ผู้เล่นจะได้รางวัลเมื่อมีสัญลักษณ์เดียวกัน 3 ตัว หรือมากกว่า ปรากฎบนแนวเส้นจากซ้ายสุดไป ทางขวา</p><p>ใน 1 LINESการชนะ จะจ่ายเพียงการชนะรวมกัน สูงสุดเท่านั้น</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและการเล่น ทั้งหมดเป็นโมฆะ</p>",
      id: "<p>Pemain akan memenangkan hadiah saat 3 atau lebih simbol yang sama muncul dalam barisan dari ujung paling kiri ke kanan.</p><p>Hanya perolehan tertinggi yang dibayarkan dari tiap kombinasi perolehan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>",
      vn: "<p>Người chơi sẽ thắng giải thưởng có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các dòng từ sát bên trái sang phải.</p><p>Chỉ trả thưởng cho lượt thắng có số điểm cao nhất cho mỗi bộ kết hợp ăn điểm.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 라인에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>승 조합 중 가장 높은 승만 지급됩니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en la línea de apuestas consecutivos.</p><p>Solo se pagan la ganancia más alta por combinación ganadora.</p><p>Si se produce un error de funcionamiento, se anularán todas las jugadas y pagos.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上ベットライン上に止まると、その絵柄のポイントが手に入ります。</p><p>各ラインの最高倍率がプレイヤーのポイントとなります。</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nas linhas da esquerda para a direita.</p><p>O jogador ganhará um prêmio com quaisquer 3 símbolos iguais que aparecem nas linhas da esquerda para a direita.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>",
      ph: "<p></p><p></p><p>Ang Hindi Paggana ay Pinapawalang-bisa ang Lahat ng Bayad at Laro.</p>",
    },
  },
  {
    type: "any3",
    name: {
      cn: "任意3",
      en: "ANY 3",
      th: "ANY 3",
      id: "ANY 3",
      vn: "ANY 3",
      ko: "ANY 3",
      es: "QUALQUER 3",
      ja: "ANY 3",
      "pt-BR": "QUALQUER 3",
      ph: "ANY 3",
    },
    content: {
      cn: "<p>任意 3 个或以上的相同图标，即可获得该图标的得分奖励！</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the reels.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัล เมื่อสัญลักษณ์เดียวกันตั้งแต่ 3 อันขึ้นไป ปรากฏบนวงล้อ</p>",
      id: "<p>Pemain akan mendapatkan hadiah saat 3 atau lebih simbol yang sama muncul dalam gulungan.</p>",
      vn: "<p>Người chơi sẽ giành được giải thưởng nếu có bất kỳ 3 biểu tượng giống nhau nào trở lên xuất hiện trên các guồng quay.</p>",
      ko: "<p>플레이어는 3개 이상의 동일한 심볼이 릴에 나타나면 상품을 획득합니다.</p>",
      es: "<p>El jugador ganará la bonificación cuando aparecen 3 o más símbolos iguales.</p>",
      ja: "<p>3つ以上の同じシンボルがリールに出現すると報酬が獲得できます。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nos molinetes.</p>",
      ph: "<p></p>",
    },
  },
  {
    type: "any5",
    name: {
      cn: "任意5",
      en: "ANY 5",
      th: "ANY 5",
      id: "ANY 5",
      vn: "ANY 5",
      ko: "ANY 5",
      es: "QUALQUER 5",
      ja: "ANY 5",
      "pt-BR": "QUALQUER 5",
      ph: "ANY 5",
    },
    content: {
      cn: `<p>任意5个或以上的[golden ball]出现在盘面上，可以获得[golden ball]中显示的得分。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>`,
      en: `<p>Player will win prizes with any 5 or more [golden ball] appearing on the reels.</p><p>Malfunction Voids All Pays and Play.</p>`,
      th: `<p>ผู้เล่นจะชนะรางวัลเมื่อสัญลักษณ์ [golden ball] 5อัน หรือมากกว่าปรากฏบนวงล้อ</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและ การเล่นทั้งหมดเป็นโมฆะ</p>`,
      id: `<p>Pemain akan mendapatkan hadiah saat 5 atau lebih [golden ball] muncul pada gulungan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>`,
      vn: `<p>Người chơi sẽ giành các giải thưởng với một trong 5 [golden ball] trở lên xuất hiện trên các cò quay.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>`,
      ko: `<p>플레이어는 릴에서 나타나는 5개 또는 그 이상의 [golden ball]을 획득 할 수 있습니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>`,
      es: `<p>Ganará el crédito de [golden ball] cuando aparecen 5 o más [golden ball].</p><p>Si se produce un error de funcionamiento, se anularán todas las jugadas y pagos.</p>`,
      ja: `<p>リールに5つ以上のいずれかの[golden ball]が出現すると報酬を獲得。</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>`,
      "pt-BR": `<p>O jogador ganhará prêmios com 5 ou mais [golden ball] aparecendo nos molinetes.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>`,
      ph: `<p>Ang manlalaro ay mananalo ng mga premyo sa alinmang 5 o higit pang [golden ball] na lumalabas sa mga reel.</p><p>Ang Hindi Paggana ay Pinapawalang-bisa ang Lahat ng Bayad at Laro.</p>`,
    },
  },
  {
    type: "any6",
    name: {
      cn: "任意6",
      en: "ANY 6",
      th: "ANY 6",
      id: "ANY 6",
      vn: "ANY 6",
      ko: "ANY 6",
      es: "QUALQUER 6",
      ja: "ANY 6",
      "pt-BR": "QUALQUER 6",
      ph: "ANY 6",
    },
    content: {
      cn: "<p>任意 6 个或以上的相同图标，即可获得该图标的得分奖励！</p>",
      en: "<p>Player will win prize with any 6 or more the same symbols appearing on the reels.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัล เมื่อสัญลักษณ์เดียวกันตั้งแต่ 6 อันขึ้นไป ปรากฏบนวงล้อ</p>",
      id: "<p>Pemain akan mendapatkan hadiah saat 6 atau lebih simbol yang sama muncul dalam gulungan.</p>",
      vn: "<p>Người chơi sẽ giành được giải thưởng nếu có bất kỳ 6 biểu tượng giống nhau nào trở lên xuất hiện trên các guồng quay.</p>",
      ko: "<p>플레이어는 6개 이상의 동일한 심볼이 릴에 나타나면 상품을 획득합니다.</p>",
      es: "<p>El jugador ganará la bonificación cuando aparecen 6 o más símbolos iguales.</p>",
      ja: "<p>6つ以上の同じシンボルがリールに出現すると報酬が獲得できます。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 6 ou mais símbolos iguais aparecendo nos molinetes.</p>",
      ph: "<p></p>",
    },
  },
  {
    type: "richways",
    name: {
      cn: "万路发",
      en: "RICH WAYS",
      th: "RICH WAYS",
      id: "RICH WAYS",
      vn: "RICH WAYS",
      ko: "RICH WAYS",
      es: "RICH WAYS",
      ja: "RICH WAYS",
      "pt-BR": "RICH WAYS",
      ph: "RICH WAYS",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现3个以上的相同图标，即可获得该图标的得分奖励。</p>",
      en: "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน 3 ตัวหรือมากกว่าปรากฎบนวงล้อต่อเนื่องจากซ้ายไปขวา</p>",
      id: "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      vn: "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ko: "<p>릴에 맨 왼쪽에서 오른쪽으로 3개 이상의 동일한 아이콘이 표시되면 해당 아이콘에 대한 득점 보상을 받습니다.</p>",
      es: "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ja: "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      "pt-BR":
        "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
      ph: "<p>Player will win prize with any 3 more the same symbols appearing on the continuous reels from leftmost to right.</p>",
    },
  },
  {
    type: "3x5ways",
    name: {
      cn: "路路发(3x5)",
      en: "REEL WAYS(3x5)",
      th: "REEL WAYS(3x5)",
      id: "REEL WAYS(3x5)",
      vn: "REEL WAYS(3x5)",
      ko: "REEL WAYS(3x5)",
      es: "FORMAS DE RODILLO(3x5)",
      ja: "路路発(3x5)",
      "pt-BR": "MANEIRAS DO MOLINETE(3x5)",
      ph: "REEL WAYS(3x5)",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现三个以上的相同图标，即可获得该图标的得分奖励。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the continuous reels from leftmost to right.</p><p>Malfunction Voids All Pays and Play.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลเมื่อมีสัญลักษณ์เหมือนกัน 3 ตัวหรือมากกว่าปรากฎบนช่องที่ต่อเนื่องกันจาก ซ้ายสุดไปทางขวา</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและ การเล่นทั้งหมดเป็นโมฆะ</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat 3 atau lebih simbol yang sama muncul dalam gulungan bersambungan dari ujung paling kiri ke kanan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>",
      vn: "<p>Người chơi sẽ thắng giải khi có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các guồng quay liên tiếp từ sát bên trái sang phải.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en los rodillos consecutivos.</p><p>Si se produce un error de funcionamiento, se anularán todas las jugadas y pagos.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上止まると、その絵柄のポイントが手に入ります！</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nos molinetes contínuos da esquerda para a direita.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>",
      ph: "<p>Player will win prize with any 3 or more the same symbols appearing on the continuous reels from leftmost to right.</p><p>Malfunction Voids All Pays and Play.</p>",
    },
  },
  {
    type: "4x5ways",
    name: {
      cn: "路路发(4x5)",
      en: "REEL WAYS(4x5)",
      th: "REEL WAYS(4x5)",
      id: "REEL WAYS(4x5)",
      vn: "REEL WAYS(4x5)",
      ko: "REEL WAYS(4x5)",
      es: "FORMAS DE RODILLO(4x5)",
      ja: "路路発(4x5)",
      "pt-BR": "MANEIRAS DO MOLINETE(4x5)",
      ph: "REEL WAYS(4x5)",
    },
    content: {
      cn: "<p>滚轮上由最左至右连续出现三个以上的相同图标，即可获得该图标的得分奖励。</p><p>游戏出现故障时，所有赔付和游戏都视为无效。</p>",
      en: "<p>Player will win prize with any 3 or more the same symbols appearing on the continuous reels from leftmost to right.</p><p>Malfunction Voids All Pays and Play.</p>",
      th: "<p>ผู้เล่นจะชนะรางวัลเมื่อมีสัญลักษณ์เหมือนกัน 3 ตัวหรือมากกว่าปรากฎบนช่องที่ต่อเนื่องกันจาก ซ้ายสุดไปทางขวา</p><p>การทำงานผิดปกติจะทำให้การจ่ายเงินและ การเล่นทั้งหมดเป็นโมฆะ</p>",
      id: "<p>Pemain akan memenangkan hadiah di saat 3 atau lebih simbol yang sama muncul dalam gulungan bersambungan dari ujung paling kiri ke kanan.</p><p>Malfungsi membatalkan Bayaran dan Permainan.</p>",
      vn: "<p>Người chơi sẽ thắng giải khi có bất kỳ 3 hình giống nhau nào trở lên xuất hiện trên các guồng quay liên tiếp từ sát bên trái sang phải.</p><p>Trục trặc Mất Tất cả Thanh toán và Chơi.</p>",
      ko: "<p>플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 3번 이상 나타나면 상품을 획득합니다.</p><p>오작동으로 인한 플레이와 배팅은 무효화 됩니다.</p>",
      es: "<p>El jugador ganará la bonificación con 3 o más símbolos iguales de izquierda a derecha en los rodillos consecutivos.</p><p>Si se produce un error de funcionamiento, se anularán todas las jugadas y pagos.</p>",
      ja: "<p>一番左のリールから同じ絵柄が連続して3個以上止まると、その絵柄のポイントが手に入ります！</p><p>不具合が生じた場合、すべての配当とゲームが無効となります。</p>",
      "pt-BR":
        "<p>O jogador ganhará um prêmio com 3 ou mais símbolos iguais aparecendo nos molinetes contínuos da esquerda para a direita.</p><p>Mau funcionamento anula todos os pagamentos e jogadas.</p>",
      ph: "<p>Player will win prize with any 3 or more the same symbols appearing on the continuous reels from leftmost to right.</p><p>Malfunction Voids All Pays and Play.</p>",
    },
  },
];
