export const menu = {
  editor: [
    {
      name: "老虎機",
      route: "slot",
    },
  ],
  management: [
    {
      name: "維護開關",
      route: "maintain",
    },
    {
      name: "使用者管理",
      route: "user-management",
    },
    {
      name: "操作記錄",
      route: "record",
    },
  ],
};

export const gameList = [
  {
    game_id: "1",
    game_name: {
      cn: "钻石水果王",
      en: "Fruit King",
      id: "Raja Buah",
      ko: "후르츠 킹",
      th: "ราชาผลไม้",
      vn: "Vua trái cây",
    },
    game_icon: {
      cn: "+60S2bATO.png",
      en: "+Fkhe7S1l.png",
      es: "+Fkhe7S1l.png",
      id: "+Fkhe7S1l.png",
      ja: "+Fkhe7S1l.png",
      ko: "+Fkhe7S1l.png",
      "pt-BR": "+Fkhe7S1l.png",
      th: "+Fkhe7S1l.png",
      vn: "+Fkhe7S1l.png",
    },
    edited: ["es", "th", "en", "ph", "cn"],
    edited_by: "QAJerry",
    created_at: "2022-02-22T06:42:45-04:00",
    updated_at: "2022-03-31T09:32:28-04:00",
  },
  {
    game_id: "10",
    game_name: {
      cn: "五福临门",
      en: "Lucky Bats",
      th: "Lucky Bats",
      tw: "五福臨門",
    },
    game_icon: {
      cn: "+xjXVC7kS.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "100",
    game_name: {
      cn: "宾果消消消",
      en: "Jellypop Humming",
    },
    game_icon: {
      cn: "+VNBd6Ayc.png",
      en: "+3MCOG55K.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "101",
    game_name: {
      cn: "星星消消乐",
      en: "Stars Matching",
    },
    game_icon: {
      cn: "+kGVBLqY0.png",
      en: "+rPymUZEF.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "1010",
    game_name: {
      cn: "五福临门JP",
      en: "LuckyBatsJP",
    },
    game_icon: {
      cn: "+4sKHOnSx.png",
      en: "+uDiEjBUu.png",
      es: "+uDiEjBUu.png",
      id: "+uDiEjBUu.png",
      ja: "+uDiEjBUu.png",
      ko: "+uDiEjBUu.png",
      "pt-BR": "+uDiEjBUu.png",
      th: "+uDiEjBUu.png",
      vn: "+uDiEjBUu.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "102",
    game_name: {
      cn: "水果派对",
      en: "Fruity Carnival",
    },
    game_icon: {
      cn: "+WkLZZcCX.png",
      en: "+xaFUUr6v.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "103",
    game_name: {
      cn: "宝石配对",
      en: "Jewel Luxury",
    },
    game_icon: {
      cn: "+hW3zCtrM.png",
      en: "+bIUsXGbx.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "104",
    game_name: {
      cn: "海滨消消乐",
      en: "Chicky Parm Parm",
      tw: "海濱消消樂",
    },
    game_icon: {
      cn: "+OyXS9pM4.png",
      en: "+JGXUTqP2.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "105",
    game_name: {
      cn: "单手跳高高",
      en: "Jumping Mobile",
      tw: "單手跳高高",
    },
    game_icon: {
      cn: "+4VA13YXI.png",
      en: "+zY84kunx.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T10:39:37-04:00",
    updated_at: "2022-03-15T05:52:58-04:00",
  },
  {
    game_id: "106",
    game_name: {
      cn: "横转跳高高",
      en: "TwistingJump",
      tw: "橫轉跳高高",
    },
    game_icon: {
      cn: "+4eaZnYo6.png",
      en: "+zQaGnncV.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "1067",
    game_name: {
      cn: "赚金蛋JP",
      en: "GoldenEggsJP",
    },
    game_icon: {
      cn: "+yMEw3Jgn.png",
      en: "+ZcBfVtjk.png",
      es: "+ZcBfVtjk.png",
      id: "+ZcBfVtjk.png",
      ja: "+ZcBfVtjk.png",
      ko: "+ZcBfVtjk.png",
      "pt-BR": "+ZcBfVtjk.png",
      th: "+ZcBfVtjk.png",
      vn: "+ZcBfVtjk.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "1074",
    game_name: {
      cn: "聚宝盆JP",
      en: "TreasureBowlJP",
    },
    game_icon: {
      cn: "+NWBL9MJw.png",
      en: "+j4A9deFB.png",
      es: "+j4A9deFB.png",
      id: "+j4A9deFB.png",
      ja: "+j4A9deFB.png",
      ko: "+j4A9deFB.png",
      "pt-BR": "+j4A9deFB.png",
      th: "+j4A9deFB.png",
      vn: "+j4A9deFB.png",
    },
    edited: ["cn", "pt-BR", "ja", "es", "ko", "vn", "id", "th", "en"],
    edited_by: "rita",
    created_at: "2022-02-25T01:54:38-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "108",
    game_name: {
      cn: "直式跳更高",
      en: "Jump Higher mobile",
    },
    game_icon: {
      cn: "+JBfJOnxC.png",
      en: "+GaiBmDHA.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T10:48:19-04:00",
    updated_at: "2022-03-25T05:54:47-04:00",
  },
  {
    game_id: "109",
    game_name: {
      cn: "单手跳起来",
      en: "Rave Jump mobile",
    },
    game_icon: {
      cn: "+KPEc767g.png",
      en: "+WLELBpjZ.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-17T03:37:31-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "11",
    game_name: {
      cn: "梦游仙境2",
      en: "Wonderland2",
      th: "Wonderland2",
      tw: "夢遊仙境2",
    },
    game_icon: {
      cn: "+T9QRJLgi.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "110",
    game_name: {
      cn: "横转跳起来",
      en: "Rave Jump Twist",
    },
    game_icon: {
      cn: "+zvkWPlpk.png",
      en: "+38XyzonK.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "111",
    game_name: {
      cn: "飞起来",
      en: "Fly Out",
    },
    game_icon: {
      cn: "+zFGZB4a6.png",
      en: "+7MT32Iqd.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-17T03:39:52-04:00",
    updated_at: "2022-03-25T06:01:07-04:00",
  },
  {
    game_id: "112",
    game_name: {
      cn: "盗法老墓",
      en: "Pyramid Raider",
    },
    game_icon: {
      cn: "+HLP1OJPV.png",
      en: "+gagjUq0E.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "th", "en", "cn"],
    edited_by: "melo",
    created_at: "2022-02-17T08:27:39-04:00",
    updated_at: "2022-03-15T03:17:14-04:00",
  },
  {
    game_id: "113",
    game_name: {
      cn: "飞天财神",
      en: "Flying Cai Shen",
    },
    game_icon: {
      cn: "+7RQ6SImw.png",
      en: "+RXsH0LQ7.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "th", "en", "cn"],
    edited_by: "QAJerry",
    created_at: "2022-03-16T06:39:28-04:00",
    updated_at: "2022-03-16T06:39:28-04:00",
  },
  {
    game_id: "114",
    game_name: {
      cn: "钻饱宝",
      en: "Gemstone",
    },
    game_icon: {
      cn: "+NnRmtMou.png",
      en: "+SymjxIi8.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "115",
    game_name: {
      cn: "冰雪女王",
      en: "Snow Queen",
    },
    game_icon: {
      cn: "+0dXk5Agh.png",
      en: "+Vn0dC7Da.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-17T06:07:44-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "116",
    game_name: {
      cn: "梦游仙境",
      en: "Wonderland",
    },
    game_icon: {
      cn: "+aY4euCmx.png",
      en: "+PpsOyPOP.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-17T06:22:25-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "117",
    game_name: {
      cn: "东方神起",
      en: "5 God beasts",
    },
    game_icon: {
      cn: "+qnIh8JcR.png",
      en: "+ttoPLrdL.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T10:17:19-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "118",
    game_name: {
      cn: "老司机",
      en: "SkrSkr",
    },
    game_icon: {
      cn: "+itDmcEd4.png",
      en: "+6PBv6ZkH.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "QAJerry",
    created_at: "2022-02-22T07:51:16-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "119",
    game_name: {
      cn: "飞单跳起来",
      en: "Free Hand Rave Jump",
    },
    game_icon: {
      cn: "+22EaDfMM.png",
      en: "+BaOTuJri.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "12",
    game_name: {
      cn: "金玉满堂",
      en: "TreasureHouse",
      th: "TreasureHouse",
      tw: "金玉滿堂",
    },
    game_icon: {
      cn: "+WPv4pxTp.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "121",
    game_name: {
      cn: "直式跳起来2",
    },
    game_icon: {
      cn: "+INdfsx0W.png",
      en: "+B6WtMKzZ.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-18T08:30:18-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "122",
    game_name: {
      cn: "印加祖玛",
      en: "Zuma Wild",
    },
    game_icon: {
      cn: "+ZWyA5Keg.png",
      en: "+bvDiSUot.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-17T04:00:02-04:00",
    updated_at: "2022-03-15T02:38:22-04:00",
  },
  {
    game_id: "123",
    game_name: {
      cn: "直式五福临门",
      en: "Lucky Bats M",
    },
    game_icon: {
      cn: "+QQZ26xab.png",
      en: "+J1Nzx0J1.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T09:44:42-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "123456",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+m9cGv470.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "124",
    game_name: {
      cn: "锁象无敌",
      en: "Invincible Elephant",
    },
    game_icon: {
      cn: "+WAOAlqjq.png",
      en: "+sOuNJHuS.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "125",
    game_name: {
      cn: "直式宙斯",
      en: "Zeus M",
    },
    game_icon: {
      cn: "+Wxjc3DVS.png",
      en: "+8KHMQ6RU.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T08:14:17-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "126",
    game_name: {
      cn: "转珠猪",
      en: "Piggy Farm",
    },
    game_icon: {
      cn: "+zAI76Zuv.png",
      en: "+12AIAzDO.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "127",
    game_name: {
      cn: "直式武圣",
      en: "God of War M ",
    },
    game_icon: {
      cn: "+HOaUNm8V.png",
      en: "+8MFGZdVV.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T07:39:40-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "128",
    game_name: {
      cn: "转大钱",
      en: "WheelMoney",
    },
    game_icon: {
      cn: "+IJ0gknyf.png",
      en: "+FvKypIO1.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T07:23:57-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "129",
    game_name: {
      cn: "直式金鸡报喜2",
      en: "Gu Gu Gu 2 M",
    },
    game_icon: {
      cn: "+5JXjqX15.png",
      en: "+hXsF4prq.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T07:15:58-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "13",
    game_name: {
      cn: "樱花妹子",
      en: "SakuraLegend",
      tw: "櫻花妹子",
    },
    game_icon: {
      cn: "+ZKhl4QNC.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "130",
    game_name: {
      cn: "偷金妹子",
      en: "Gold Stealer",
    },
    game_icon: {
      cn: "+d7cZ0O3N.png",
      en: "+2LfJumfY.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T07:07:59-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "131",
    game_name: {
      cn: "直式发财神",
      en: "Fa Cai Shen M",
    },
    game_icon: {
      cn: "+Yo0Bbfhx.png",
      en: "+vIhTvyji.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T06:44:25-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "132",
    game_name: {
      cn: "再喵一个",
      en: "Meow",
    },
    game_icon: {
      cn: "+88oACPAy.png",
      en: "+7JNuaTTN.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T05:52:50-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "133",
    game_name: {
      cn: "直式鸿福齐天",
      en: "Good Fortune M",
    },
    game_icon: {
      cn: "+JKFztroD.png",
      en: "+Muuo7IQ4.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "134",
    game_name: {
      cn: "家里有矿",
      en: "Mine at home",
    },
    game_icon: {
      cn: "+jodoK8rm.png",
      en: "+fg6C5emF.png",
      es: "+fg6C5emF.png",
      id: "+fg6C5emF.png",
      ja: "+fg6C5emF.png",
      ko: "+fg6C5emF.png",
      "pt-BR": "+fg6C5emF.png",
      th: "+fg6C5emF.png",
      vn: "+fg6C5emF.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "135",
    game_name: {
      cn: "直式金鸡报喜",
      en: "Gu Gu Gu M",
    },
    game_icon: {
      cn: "+cl0I2V9I.png",
      en: "+OccXMvsd.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-21T03:49:29-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "136",
    game_name: {
      cn: "奔跑吧猛兽",
      en: "Running Animals",
    },
    game_icon: {
      cn: "+OYgmCumw.png",
      en: "+OEzu2TxD.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-21T03:50:19-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "137",
    game_name: {
      cn: "直式蹦迪",
      en: "Disco Night M",
    },
    game_icon: {
      cn: "+1pWBTFay.png",
      en: "+RtrOsdaR.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T05:35:20-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "138",
    game_name: {
      cn: "跳过来",
      en: "Move n' Jump",
    },
    game_icon: {
      cn: "+Ilow8ID7.png",
      en: "+pUK030lr.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T05:28:43-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "139",
    game_name: {
      cn: "直式火烧连环船",
      en: "Fire Chibi M",
    },
    game_icon: {
      cn: "+bWL5VLaU.png",
      en: "+2ydsCVXV.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T05:22:01-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "14",
    game_name: {
      cn: "绝赢巫师",
      en: "RichWitch",
      tw: "絕贏巫師",
    },
    game_icon: {
      cn: "+bTz6iAbc.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "140",
    game_name: {
      cn: "火烧连环船2",
      en: "Fire Chibi 2",
    },
    game_icon: {
      cn: "+db5hHSs5.png",
      en: "+zeAzPHVB.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T03:05:26-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "141",
    game_name: {
      cn: "圣诞来啦",
      en: "Xmas",
    },
    game_icon: {
      cn: "+V0pwyghB.png",
      en: "+CpEzUjEd.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "142",
    game_name: {
      cn: "火神",
      en: "Hephaestus",
    },
    game_icon: {
      cn: "+zXVipci8.png",
      en: "+31qyLrb2.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T03:00:03-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "143",
    game_name: {
      cn: "发财福娃",
      en: "Fa Cai Fu Wa",
    },
    game_icon: {
      cn: "+BQ1ueS7H.png",
      en: "+CMDpUcV7.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "144",
    game_name: {
      cn: "钻更多",
      en: "Diamond treasure",
    },
    game_icon: {
      cn: "+B5D8CWUX.png",
      en: "+Mu1a6J0d.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T02:50:57-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "145",
    game_name: {
      cn: "印金工厂",
      en: "Casting Gold",
    },
    game_icon: {
      cn: "+r3kLmwF5.png",
      en: "+xwK6040H.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "146",
    game_name: {
      cn: "九连宝灯",
      en: "Sky Lantern",
    },
    game_icon: {
      cn: "+gjp54jHl.png",
      en: "+AUN4LME1.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T02:36:54-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "147",
    game_name: {
      cn: "花开富贵",
      en: "Flower Fortunes",
    },
    game_icon: {
      cn: "+D3pkZaXH.png",
      en: "+3is7ZyOl.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "148",
    game_name: {
      cn: "有如神柱",
      en: "Fortune Totem",
    },
    game_icon: {
      cn: "+th8bfknL.png",
      en: "+wTXE7f95.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "149",
    game_name: {
      cn: "龙舟",
      en: "Dragon Boat",
    },
    game_icon: {
      cn: "+1CyaeKNL.png",
      en: "+V9ZiR0WV.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "15",
    game_name: {
      cn: "金鸡报喜",
      en: "GuGuGu",
      th: "GuGuGu",
      tw: "金雞報喜",
    },
    game_icon: {
      cn: "+IFeEfAq5.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "150",
    game_name: {
      cn: "寿星大发",
      en: "Shou-Xin",
    },
    game_icon: {
      cn: "+Pecz4VPl.png",
      en: "+scwq2K9q.png",
    },
    edited: ["es", "pt-BR", "ja", "vn", "id", "ko", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-16T01:52:14-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "151",
    game_name: {
      cn: "龙虎水果机",
      en: "Dragon Tiger Fruit Slot",
    },
    game_icon: {
      cn: "+uiFQPLmC.png",
      en: "+OiBAzEgY.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "152",
    game_name: {
      cn: "双飞",
      en: "Double Fly",
    },
    game_icon: {
      cn: "+MFkUiNXY.png",
      en: "+H1Mjnq2a.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "153",
    game_name: {
      cn: "六颗糖",
      en: "Six Candy",
    },
    game_icon: {
      cn: "+mw5aq06E.png",
      en: "+h58qXy8j.png",
    },
    edited: ["pt-BR", "es", "ja", "en", "vn", "id", "th", "ko", "cn"],
    edited_by: "rita",
    created_at: "2022-02-15T12:11:33-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "154",
    game_name: {
      cn: "宙斯他爹",
      en: "Kronos",
    },
    game_icon: {
      cn: "+vRhvnZ7M.png",
      en: "+SLSCP1Dd.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "155",
    game_name: {
      cn: "东方发发发",
      en: "OG Fa Fa Fa",
    },
    game_icon: {
      cn: "+vXgwDz54.jpg",
      en: "+SDY6AekO.jpg",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T10:37:42-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "156",
    game_name: {
      cn: "东方传奇",
      en: "OG Legend",
    },
    game_icon: {
      cn: "+YVFdHlJe.jpg",
      en: "+IYZjSxCV.jpg",
    },
    edited: ["pt-BR", "ja", "es", "ko", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T03:50:24-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "157",
    game_name: {
      cn: "五形拳",
      en: "5 Boxing",
    },
    game_icon: {
      cn: "+DFJGjyCj.png",
      en: "+4aI0yoPF.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "159",
    game_name: {
      cn: "赢光派对",
      en: "Neon Booze-Up",
    },
    game_icon: {
      cn: "+54vN1SuE.png",
      en: "+waGAJBeF.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "16",
    game_name: {
      cn: "五行",
      en: "Super5",
      tw: "五行",
    },
    game_icon: {
      cn: "+97Qmab3q.png",
      en: "+tgDT2dwq.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "160",
    game_name: {
      cn: "发财神2",
      en: "5 Dorgons Grand",
    },
    game_icon: {
      cn: "+R9EeP2KS.png",
      en: "+hFlPadSN.png",
    },
    edited: [],
    edited_by: "rita",
    created_at: "2022-03-09T06:54:06-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "161",
    game_name: {
      cn: "大力神",
      en: "Break Away Deluxe",
    },
    game_icon: {
      cn: "+uHxByT9z.png",
      en: "+5OeZYFbt.png",
    },
    edited: ["ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-24T07:23:50-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "162",
    game_name: {
      cn: "财神宾果",
      en: "Cai Shen Bingo",
    },
    game_icon: {
      cn: "+ajwfZvSx.png",
      en: "+yBcFJpiG.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "163",
    game_name: {
      cn: "哪吒再临",
      en: "King of Glod",
    },
    game_icon: {
      cn: "+rP9NwRZH.png",
      en: "+kd7Tw8nE.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "164",
    game_name: {
      cn: "Lucky Stars 幸运星",
      en: "Lucky Stars",
    },
    game_icon: {
      cn: "+s69YDrbq.png",
      en: "+wcSikchB.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "165",
    game_name: {
      cn: "豪运十倍",
      en: "Tenfold Lottery",
    },
    game_icon: {
      cn: "+EfFXpvlD.png",
      en: "+9hV7jjRB.png",
      es: "+9hV7jjRB.png",
      id: "+9hV7jjRB.png",
      ja: "+9hV7jjRB.png",
      ko: "+9hV7jjRB.png",
      "pt-BR": "+9hV7jjRB.png",
      th: "+9hV7jjRB.png",
      vn: "+9hV7jjRB.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "166",
    game_name: {
      cn: "福禄寿",
      en: "Thunderstruck ⅱ",
    },
    game_icon: {
      cn: "+CJAKVraz.png",
      en: "+hTQS743R.png",
      es: "+hTQS743R.png",
      id: "+hTQS743R.png",
      ja: "+hTQS743R.png",
      ko: "+hTQS743R.png",
      "pt-BR": "+hTQS743R.png",
      th: "+hTQS743R.png",
      vn: "+hTQS743R.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "167",
    game_name: {
      cn: "东方福兽",
      en: " Fortune Beasts",
    },
    game_icon: {
      cn: "+rS1paBWU.png",
      en: "+BEXMxJjF.png",
      es: "+BEXMxJjF.png",
      id: "+BEXMxJjF.png",
      ja: "+BEXMxJjF.png",
      ko: "+BEXMxJjF.png",
      "pt-BR": "+BEXMxJjF.png",
      th: "+BEXMxJjF.png",
      vn: "+BEXMxJjF.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "168",
    game_name: {
      cn: "猪事大吉",
      en: "Golden Pigs",
    },
    game_icon: {
      cn: "+gLM6178T.png",
      en: "+7xjdjKIw.png",
      es: "+7xjdjKIw.png",
      id: "+7xjdjKIw.png",
      ja: "+7xjdjKIw.png",
      ko: "+7xjdjKIw.png",
      "pt-BR": "+7xjdjKIw.png",
      th: "+7xjdjKIw.png",
      vn: "+7xjdjKIw.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "17",
    game_name: {
      cn: "祥狮献瑞",
      en: "GreatLion",
      th: "GreatLion",
      tw: "祥獅獻瑞",
    },
    game_icon: {
      cn: "+oJmY6TtD.png",
      en: "+7lpaRTM4.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "170",
    game_name: {
      cn: "中国锦鲤",
      en: "Lucky Fish",
    },
    game_icon: {
      cn: "+b7ibIdwk.png",
      en: "+PDwqGS12.png",
      es: "+PDwqGS12.png",
      id: "+PDwqGS12.png",
      ja: "+PDwqGS12.png",
      ko: "+PDwqGS12.png",
      "pt-BR": "+PDwqGS12.png",
      th: "+PDwqGS12.png",
      vn: "+PDwqGS12.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "171",
    game_name: {
      cn: "众神之门",
      en: "Gate Of The Gods",
    },
    game_icon: {
      cn: "+I2iZX4dP.png",
      en: "+nBhPOfaN.png",
      es: "+nBhPOfaN.png",
      id: "+nBhPOfaN.png",
      ja: "+nBhPOfaN.png",
      ko: "+nBhPOfaN.png",
      "pt-BR": "+nBhPOfaN.png",
      th: "+nBhPOfaN.png",
      vn: "+nBhPOfaN.png",
    },
    edited: ["cn", "en"],
    edited_by: "QAJerry",
    created_at: "2022-03-18T06:05:44-04:00",
    updated_at: "2022-03-18T06:05:44-04:00",
  },
  {
    game_id: "173",
    game_name: {
      cn: "666",
      en: "6 Toros666",
    },
    game_icon: {
      cn: "+doJvUDWg.png",
      en: "+51KHqo7L.png",
      es: "+51KHqo7L.png",
      id: "+51KHqo7L.png",
      ja: "+51KHqo7L.png",
      ko: "+51KHqo7L.png",
      "pt-BR": "+51KHqo7L.png",
      th: "+51KHqo7L.png",
      vn: "+51KHqo7L.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "174",
    game_name: {
      cn: "双喜鱼虾蟹",
      en: "Fish-Prawn-Crab",
      tw: "双喜魚蝦蟹",
    },
    game_icon: {
      cn: "+qfofh08n.png",
      en: "+sEZJoK53.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "175",
    game_name: {
      cn: "解锁大盗",
      en: "UnlockVault",
    },
    game_icon: {
      cn: "+fGWnPjIP.png",
      en: "+h9HAvVA8.png",
      es: "+h9HAvVA8.png",
      id: "+h9HAvVA8.png",
      ja: "+h9HAvVA8.png",
      ko: "+h9HAvVA8.png",
      "pt-BR": "+h9HAvVA8.png",
      th: "+h9HAvVA8.png",
      vn: "+h9HAvVA8.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "179",
    game_name: {
      cn: "跳高高2",
      en: "Jump High 2",
      tw: "跳高高2",
    },
    game_icon: {
      cn: "+0uizPHG8.png",
      en: "+pRr78nRu.png",
      ko: "+1xuVDF8Z.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T04:00:04-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "18",
    game_name: {
      cn: "雀王",
      en: "MahjongKing",
      th: "MahjongKing",
      tw: "雀王",
    },
    game_icon: {
      cn: "+l51raxPi.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "180",
    game_name: {
      cn: "金鸡报囍3",
      en: "Gu Gu Gu3",
      tw: "金雞報囍3",
    },
    game_icon: {
      cn: "+PvWZrjyl.png",
      en: "+HcHMXnec.png",
      es: "+HcHMXnec.png",
      id: "+HcHMXnec.png",
      ja: "+HcHMXnec.png",
      ko: "+HcHMXnec.png",
      "pt-BR": "+HcHMXnec.png",
      th: "+HcHMXnec.png",
      vn: "+HcHMXnec.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T05:42:59-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "182",
    game_name: {
      cn: "雷神2",
      en: "Thor 2",
      tw: "雷神2",
    },
    game_icon: {
      cn: "+AMk1ktR8.png",
      en: "+WRGdSztj.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-24T08:08:19-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "183",
    game_name: {
      cn: "野狼Disco",
      en: "Wild Wolf Disco",
      tw: "野狼Disco",
    },
    game_icon: {
      cn: "+zg10K3T8.png",
      en: "+KbuoiUKJ.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T05:57:45-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "184",
    game_name: {
      cn: "六颗扭蛋",
      en: "Six capsules",
      tw: "六顆扭蛋",
    },
    game_icon: {
      cn: "+McgVKwtE.png",
      en: "+PXvRC9td.png",
      id: "+PXvRC9td.png",
      ko: "+PXvRC9td.png",
      th: "+PXvRC9td.png",
      vn: "+PXvRC9td.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T09:49:00-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "185",
    game_name: {
      cn: "龙珠",
      en: "Dragon Ball",
    },
    game_icon: {
      cn: "+m1JsWjIj.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T10:12:24-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "187",
    game_name: {
      cn: "咏春",
      en: "Wing Chun",
    },
    game_icon: {
      cn: "+ZOr7TfB9.png",
      en: "+vCh6HVkm.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-04-13T21:48:25-04:00",
    updated_at: "2022-04-13T21:48:25-04:00",
  },
  {
    game_id: "19",
    game_name: {
      cn: "风火轮",
      en: "HotSpin",
      th: "HotSpin",
      tw: "風火輪",
    },
    game_icon: {
      cn: "+yXVRx7yl.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "196",
    game_name: {
      cn: "十倍金喜",
      en: "Tenfold Eggs",
    },
    game_icon: {
      cn: "+bHAosgpd.png",
      en: "+2qudkR5b.png",
      th: "+wNAr2R2b.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "2",
    game_name: {
      cn: "棋圣",
      en: "GodOfChess",
      tw: "棋聖",
    },
    game_icon: {
      cn: "+fHm7VSAD.png",
    },
    edited: [],
    edited_by: "rita",
    created_at: "2022-03-09T06:53:38-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "20",
    game_name: {
      cn: "发发发",
      en: "888",
      th: "888",
      tw: "發發發",
    },
    game_icon: {
      cn: "+LPUo3cHB.png",
      en: "+xYuLxllF.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "200",
    game_name: {
      cn: "跑跑爱丽丝",
      en: "Alice Run",
    },
    game_icon: {
      cn: "+AUPyIP0K.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "201",
    game_name: {
      cn: "拳霸",
      en: "Ong-Bak",
    },
    game_icon: {
      cn: "+zPckTiVR.png",
      en: "+95HTvVuU.png",
      es: "+95HTvVuU.png",
      id: "+95HTvVuU.png",
      ja: "+95HTvVuU.png",
      ko: "+95HTvVuU.png",
      "pt-BR": "+95HTvVuU.png",
      th: "+95HTvVuU.png",
      vn: "+95HTvVuU.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T06:39:35-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "202",
    game_name: {
      cn: "舞媚娘",
      en: "Oriental Beauty",
    },
    game_icon: {
      cn: "+tSNFEJYM.png",
      en: "+Gq0edJ00.png",
      es: "+Gq0edJ00.png",
      id: "+Gq0edJ00.png",
      ja: "+Gq0edJ00.png",
      ko: "+Gq0edJ00.png",
      "pt-BR": "+Gq0edJ00.png",
      th: "+Gq0edJ00.png",
      vn: "+Gq0edJ00.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-23T06:45:13-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "203",
    game_name: {
      cn: "嗨起来",
      en: "RaveHigh",
    },
    game_icon: {
      cn: "+iHdoE42t.png",
      en: "+YfaHDUUG.png",
      es: "+YfaHDUUG.png",
      id: "+YfaHDUUG.png",
      ja: "+YfaHDUUG.png",
      ko: "+YfaHDUUG.png",
      "pt-BR": "+YfaHDUUG.png",
      th: "+YfaHDUUG.png",
      vn: "+YfaHDUUG.png",
    },
    edited: ["pt-BR", "ja", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-23T06:49:28-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "204",
    game_name: {
      cn: "幸运球",
      en: "LuckyBall",
    },
    game_icon: {
      cn: "+wTaQIiIr.png",
      en: "+5xEvgyCZ.png",
      es: "+5xEvgyCZ.png",
      id: "+5xEvgyCZ.png",
      ja: "+5xEvgyCZ.png",
      ko: "+5xEvgyCZ.png",
      "pt-BR": "+5xEvgyCZ.png",
      th: "+5xEvgyCZ.png",
      vn: "+5xEvgyCZ.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T06:54:58-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "205",
    game_name: {
      cn: "蹦迪",
      en: "DiscoNight",
    },
    game_icon: {
      cn: "+iWPKELBe.png",
      en: "+Os1aJdT6.png",
      es: "+Os1aJdT6.png",
      id: "+Os1aJdT6.png",
      ja: "+Os1aJdT6.png",
      ko: "+Os1aJdT6.png",
      "pt-BR": "+Os1aJdT6.png",
      th: "+Os1aJdT6.png",
      vn: "+Os1aJdT6.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-23T07:01:15-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "206",
    game_name: {
      cn: "甜蜜暴击",
      en: "Sweet POP",
    },
    game_icon: {
      cn: "+Oo1RQFKG.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "207",
    game_name: {
      cn: "泰式骰宝",
      en: "Thai HILO",
    },
    game_icon: {
      cn: "+cJQ55uqV.jpeg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "21",
    game_name: {
      cn: "野狼传说",
      en: "Big Wolf",
      th: "Big Wolf",
      tw: "野狼傳說",
    },
    game_icon: {
      cn: "+Eb4SXqbJ.png",
      en: "+5sycRF3D.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "214",
    game_name: {
      cn: "忍者浣熊",
      en: "Ninja Raccoon",
    },
    game_icon: {
      cn: "+WllkC8Fm.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "216",
    game_name: {
      cn: "色碟",
      en: "Xoc Dia",
    },
    game_icon: {
      cn: "+6C9CP9hB.png",
      en: "+GDajQ54z.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "217",
    game_name: {
      cn: "麻将水果盘",
      en: "Mahjong Fruit",
    },
    game_icon: {
      cn: "+v3nvMWEw.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "218",
    game_name: {
      cn: "达拉崩吧",
      en: "Dollar Bomb",
    },
    game_icon: {
      cn: "+ifsWpWjg.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "22",
    game_name: {
      cn: "庶务西游二课",
      en: "MonkeyOfficeLegend",
      th: "MonkeyOfficeLegend",
      tw: "庶務西遊二課",
    },
    game_icon: {
      cn: "+Y60pZND7.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "220",
    game_name: {
      cn: "泰市集",
      en: "Floating Market",
    },
    game_icon: {
      cn: "+ZKDqqsFy.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "221",
    game_name: {
      cn: "狄仁杰四大天王",
      en: "Detective Dee 2",
    },
    game_icon: {
      cn: "+tMzW1Lp9.png",
      en: "+ZhprKv5c.png",
      es: "+ZhprKv5c.png",
      id: "+ZhprKv5c.png",
      ja: "+ZhprKv5c.png",
      ko: "+ZhprKv5c.png",
      "pt-BR": "+ZhprKv5c.png",
      th: "+ZhprKv5c.png",
      vn: "+ZhprKv5c.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "23",
    game_name: {
      cn: "金元宝",
      en: "YuanBao",
      th: "YuanBao",
      tw: "金元寶",
    },
    game_icon: {
      cn: "+3zseeXyB.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "24",
    game_name: {
      cn: "跳起来2",
      en: "RaveJump2",
      th: "RaveJump2",
      tw: "跳起來2",
    },
    game_icon: {
      cn: "+Mkk3GGy8.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "25",
    game_name: {
      cn: "扑克拉霸",
      en: "PokerSLOT",
      th: "PokerSLOT",
      tw: "撲克拉霸",
    },
    game_icon: {
      cn: "+sa7oU84Q.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "26",
    game_name: {
      cn: "777",
      en: "777",
      th: "777",
      tw: "777",
    },
    game_icon: {
      cn: "+fEXruAg3.png",
      en: "+TLC28bsL.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "27",
    game_name: {
      cn: "魔法世界",
      en: "Magic World",
      th: "Magic World",
      tw: "魔法世界",
    },
    game_icon: {
      cn: "+CUyEVaHB.png",
      en: "+Mrwof0Dn.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "28",
    game_name: {
      cn: "食神",
      en: "God of Cookery",
      tw: "食神",
    },
    game_icon: {
      cn: "+Fqi8yubG.png",
      en: "+YsAZtszW.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "29",
    game_name: {
      cn: "水世界",
      en: "WaterWorld",
      tw: "水世界",
    },
    game_icon: {
      cn: "+TZov3J3v.png",
      en: "+GfVEmotT.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "3",
    game_name: {
      cn: "血吻",
      en: "VampireKiss",
      tw: "血之吻",
    },
    game_icon: {
      cn: "+Teso0I5l.png",
      en: "+4e0xAMIv.png",
      tw: "+g",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "30",
    game_name: {
      cn: "三国序",
      en: "Warrior Legend",
      th: "Warrior Legend",
      tw: "三國序",
    },
    game_icon: {
      cn: "+yt9qh0n9.png",
      en: "+f5i7AqtS.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "301",
    game_name: {
      cn: "战西游",
      en: "The Monkey King",
      es: "The Monkey King",
      in: "The Monkey King",
      ja: "The Monkey King",
      ko: "The Monkey King",
      "pt-BR": "The Monkey King",
      th: "The Monkey King",
      vn: "The Monkey King",
    },
    game_icon: {
      cn: "+yhmt7O2J.png",
      en: "+sV4k0hh9.png",
      es: "+sV4k0hh9.png",
      id: "+sV4k0hh9.png",
      ja: "+sV4k0hh9.png",
      ko: "+sV4k0hh9.png",
      "pt-BR": "+sV4k0hh9.png",
      th: "+sV4k0hh9.png",
      vn: "+sV4k0hh9.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "31",
    game_name: {
      cn: "武圣",
      en: "God of War",
      th: "God of War",
      tw: "武聖",
    },
    game_icon: {
      cn: "+EDBYBPEj.png",
      en: "+XdsdCyXK.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "32",
    game_name: {
      cn: "通天神探狄仁杰",
      en: "Detective Dee",
      th: "Detective Dee",
      tw: "通天神探狄仁傑",
    },
    game_icon: {
      cn: "+oQNgK0Al.png",
      en: "+7SVoxQzw.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "33",
    game_name: {
      cn: "火烧连环船",
      en: "Fire Chibi",
      th: "Fire Chibi",
      tw: "火燒連環船",
    },
    game_icon: {
      cn: "+WyhSnGQg.png",
      en: "+uxeVBYcn.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "34",
    game_name: {
      cn: "地鼠战役",
      en: "Gophers War",
      th: "Gophers War",
      tw: "地鼠戰役",
    },
    game_icon: {
      cn: "+GZosaUcT.png",
      en: "+x5yPsK1M.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "35",
    game_name: {
      cn: "疯狂哪吒",
      en: "Crazy NuoZha",
      tw: "瘋狂哪吒",
    },
    game_icon: {
      cn: "+7lg3EUWz.png",
      en: "+UFUdbq0z.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "36",
    game_name: {
      cn: "夜店大亨",
      en: "Pub Tycoon",
      tw: "夜店大亨",
    },
    game_icon: {
      cn: "+w9JLXWCU.png",
      en: "+aB1Lgsld.png",
      es: "+aB1Lgsld.png",
      id: "+aB1Lgsld.png",
      ja: "+aB1Lgsld.png",
      ko: "+aB1Lgsld.png",
      "pt-BR": "+aB1Lgsld.png",
      th: "+aB1Lgsld.png",
      vn: "+aB1Lgsld.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "37",
    game_name: {
      cn: "虎虎虎",
      en: "HuHuHu",
      tw: "虎虎虎",
    },
    game_icon: {
      cn: "+1bE4IRS9.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "38",
    game_name: {
      cn: "舞力全开",
      en: "All Wilds",
      th: "All Wilds",
      tw: "舞力全開",
    },
    game_icon: {
      cn: "+f0RIbZvL.png",
      en: "+DOrI7onb.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "39",
    game_name: {
      cn: "飞天",
      en: "Apsaras",
      th: "Apsaras",
      tw: "飛天",
    },
    game_icon: {
      cn: "+QkJRwTQw.png",
      en: "+HEu1Pcbb.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "4",
    game_name: {
      cn: "森林泰后",
      en: "WildTarzan",
      ko: "와일드 타잔",
      tw: "森林泰后",
      vn: "Tarzan hoang dã",
    },
    game_icon: {
      cn: "+CYmSghDM.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "40",
    game_name: {
      cn: "镖王争霸",
      en: "Darts Championship",
      th: "Darts Championship",
      tw: "鏢王爭霸",
    },
    game_icon: {
      cn: "+jomsLHQD.png",
      en: "+zB5ezEIq.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "41",
    game_name: {
      cn: "水球大战",
      en: "Water Balloons",
      th: "Water Balloons",
      tw: "水球大戰",
    },
    game_icon: {
      cn: "+uUZtddeA.png",
      en: "+rYUQYlY6.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "42",
    game_name: {
      cn: "福尔摩斯",
      en: "Sherlock Holmes",
      th: "Sherlock Holmes",
      tw: "福爾摩斯",
    },
    game_icon: {
      cn: "+C8lTA6eu.png",
      en: "+N29sgidO.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "43",
    game_name: {
      cn: "恭贺新禧",
      en: "Gong He Xin Xi",
      th: "Gong He Xin Xi",
      tw: "恭賀新禧",
    },
    game_icon: {
      cn: "+7DelCiiF.png",
      en: "+c5XxXGgh.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "44",
    game_name: {
      cn: "豪华水果王",
      en: "Fruit King II",
      tw: "豪華水果王",
    },
    game_icon: {
      cn: "+WAVynGh8.png",
      en: "+JnxxReWv.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "45",
    game_name: {
      cn: "超级发",
      en: "Super8",
      th: "Super8",
      tw: "超級發",
    },
    game_icon: {
      cn: "+hBAGqzHg.png",
      en: "+B08rmERN.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "46",
    game_name: {
      cn: "狼月",
      en: "Wolf Moon",
      tw: "狼月",
    },
    game_icon: {
      cn: "+8NYKnMSo.png",
      en: "+OIPQMNEH.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "47",
    game_name: {
      cn: "法老宝藏",
      en: "Pharaoh's Gold",
      th: "Pharaoh's Gold",
      tw: "法老寶藏",
    },
    game_icon: {
      cn: "+CHZtRg9P.png",
      en: "+17speEbM.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "48",
    game_name: {
      cn: "莲",
      en: "Lotus",
      tw: "蓮",
    },
    game_icon: {
      cn: "+j1r2zp17.png",
      en: "+cZ0dP5Ts.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "49",
    game_name: {
      cn: "寂寞星球",
      en: "Lonely Planet",
      tw: "寂寞星球",
    },
    game_icon: {
      cn: "+f4KxaCtN.png",
      en: "+nIbfa1mZ.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "5",
    game_name: {
      cn: "金大款",
      en: "Mr.Rich",
      ko: "미스터 리치",
      th: "Mr.Rich",
      tw: "金大款",
      vn: "Ông Rich",
    },
    game_icon: {
      cn: "+cPsyO0gi.png",
      en: "+p6IdSgsl.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "50",
    game_name: {
      cn: "鸿福齐天",
      en: "Good Forture",
      tw: "鴻福齊天",
    },
    game_icon: {
      cn: "+te30PtQX.png",
      en: "+uMhLNEp6.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "51",
    game_name: {
      cn: "嗨爆大马戏",
      en: "Ecstatic Circus",
      th: "Ecstatic Circus",
      tw: "嗨爆大馬戲",
    },
    game_icon: {
      cn: "+65fSNAiZ.png",
      en: "+l6yhx0hx.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "52",
    game_name: {
      cn: "跳高高",
      en: "Jump High",
      tw: "跳高高",
    },
    game_icon: {
      cn: "+rfMDw76U.png",
      en: "+yeTky71W.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "53",
    game_name: {
      cn: "来电99",
      en: "Love Night",
      th: "Love Night",
      tw: "來電99",
    },
    game_icon: {
      cn: "+Ugr1w6ja.png",
      en: "+zMkHecCX.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "54",
    game_name: {
      cn: "火草泥马",
      en: "Funny Alpaca",
    },
    game_icon: {
      cn: "+CXkUCQYX.png",
      en: "+CCUV6GQb.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "55",
    game_name: {
      cn: "魔龙传奇",
      en: "Dragon Heart",
    },
    game_icon: {
      cn: "+7qwPhcds.png",
      en: "+aGRJyWxE.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "56",
    game_name: {
      cn: "黯夜公爵",
      en: "Dracula",
    },
    game_icon: {
      cn: "+UH24X65o.png",
      en: "+xM9I9QdA.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "57",
    game_name: {
      cn: "神兽争霸",
      en: "The Beast War",
    },
    game_icon: {
      cn: "+cXpsYg1C.png",
      en: "+3xReDmGC.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "58",
    game_name: {
      cn: "金鸡报囍2",
      en: "GuGuGu2",
    },
    game_icon: {
      cn: "+ZJmCQwBf.png",
      en: "+eQUTVWwM.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "59",
    game_name: {
      cn: "夏日猩情",
      en: "SummerMood",
    },
    game_icon: {
      cn: "+AlUsFQgs.png",
      en: "+gcBw8m09.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "6",
    game_name: {
      cn: "1945",
      en: "1945",
      ko: "1945",
      th: "1945",
      tw: "1945",
      vn: "1945",
    },
    game_icon: {
      cn: "+xQHMKXis.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "60",
    game_name: {
      cn: "森林舞会",
      en: "JungleParty",
    },
    game_icon: {
      cn: "+ZjsV7nLt.png",
      en: "+Z8tJ6URE.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "61",
    game_name: {
      cn: "天天吃豆",
      en: "Mr. Bean",
    },
    game_icon: {
      cn: "+u4hcqrZB.png",
      en: "+m5IXD0lv.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "62",
    game_name: {
      cn: "非常钻",
      en: "Super Diamonds",
    },
    game_icon: {
      cn: "+d377GC4i.png",
      en: "+XbfdMDRm.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "63",
    game_name: {
      cn: "寻龙诀",
      en: "The Ghouls",
    },
    game_icon: {
      cn: "+BYYSECQy.png",
      en: "+idvypZ0K.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "64",
    game_name: {
      cn: "宙斯",
      en: "Zeus",
    },
    game_icon: {
      cn: "+tirFJF01.png",
      en: "+Y0fRJAHw.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "65",
    game_name: {
      cn: "足球世界杯",
      en: "GoldenKick",
    },
    game_icon: {
      cn: "+19v1VheV.png",
      en: "+0NardNgU.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "66",
    game_name: {
      cn: "火爆777",
      en: "Fire777",
    },
    game_icon: {
      cn: "+pM4zNCHg.png",
      en: "+OF2nwFZM.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "67",
    game_name: {
      cn: "赚金蛋",
      en: "GoldenEggs",
    },
    game_icon: {
      cn: "+BwWx4aqd.png",
      en: "+tAxlRr7L.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "68",
    game_name: {
      cn: "悟空偷桃",
      en: "WuKong&Peaches",
    },
    game_icon: {
      cn: "+MClRBkO0.png",
      en: "+0KctmvTG.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "69",
    game_name: {
      cn: "發財神",
      en: "Fa Cai Shen",
    },
    game_icon: {
      cn: "+1T3ZaT1l.png",
      en: "+V53zf3yY.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "7",
    game_name: {
      cn: "跳起来",
      en: "RaveJump",
      ko: "레이브 점프",
      tw: "跳起來",
      vn: "Mê sảng",
    },
    game_icon: {
      cn: "+jYRsEITB.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "70",
    game_name: {
      cn: "万饱龙",
      en: "WanBaoDino",
    },
    game_icon: {
      cn: "+bA77CfdL.png",
      en: "+iSYzExKo.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "72",
    game_name: {
      cn: "好运年年",
      en: "HappyRichYear",
    },
    game_icon: {
      cn: "+l2GQIhw2.png",
      en: "+GIrO0snQ.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "73",
    game_name: {
      cn: "万兽之王",
      en: "LionKing",
    },
    game_icon: {
      cn: "+8AMNfqZy.jpg",
      en: "+8zYy68P0.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "74",
    game_name: {
      cn: "聚宝盆",
      en: "Treasure Bowl",
    },
    game_icon: {
      cn: "+sSzcYrUe.png",
      en: "+ESogCyv6.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "75",
    game_name: {
      cn: "金宝熊",
      en: "ThreePandas",
    },
    game_icon: {
      cn: "+2s5cfZ5m.png",
      en: "+1tYwELMq.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "76",
    game_name: {
      cn: "旺旺旺",
      en: "WonWonWon",
    },
    game_icon: {
      cn: "+AVH33GBS.png",
      en: "+D6SIAqM5.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "77",
    game_name: {
      cn: "火凤凰",
      en: "RedPhoenix",
    },
    game_icon: {
      cn: "+VHkAEPkO.png",
      en: "+AKxQjuqq.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "78",
    game_name: {
      cn: "阿波罗",
      en: "Apollo",
    },
    game_icon: {
      cn: "+aXhzzhDl.png",
      en: "+oLCqtXad.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "79",
    game_name: {
      cn: "变色龙",
      en: "Chameleon",
    },
    game_icon: {
      cn: "+LNxYl2T6.png",
      en: "+FFRRdPcq.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "8",
    game_name: {
      cn: "甜蜜蜜",
      en: "SoSweet",
      ko: "소 스위트",
      th: "SoSweet",
      tw: "甜蜜蜜",
      vn: "Thật ngọt ngào",
    },
    game_icon: {
      cn: "+NyOKrOCY.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "80",
    game_name: {
      cn: "传奇海神",
      en: "Poseidon",
    },
    game_icon: {
      cn: "+jPztjlnR.png",
      en: "+nME3aoZu.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "81",
    game_name: {
      cn: "金银岛",
      en: "Treasure Island",
    },
    game_icon: {
      cn: "+oL6JO8dU.png",
      en: "+Fed5201k.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "83",
    game_name: {
      cn: "火之女王",
      en: "FireQueen",
    },
    game_icon: {
      cn: "+wMIjk0as.png",
      en: "+Xte8OfyS.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "84",
    game_name: {
      cn: "奇幻魔术",
      en: "WildMagic",
    },
    game_icon: {
      cn: "+SC7vuMsk.png",
      en: "+QuPWoxUS.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "86",
    game_name: {
      cn: "牛逼快跑",
      en: "Running Toro",
    },
    game_icon: {
      cn: "+CPXOz0IL.png",
      en: "+w73Y4I5Z.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "87",
    game_name: {
      cn: "集电宝",
      en: "GettingEnergies",
    },
    game_icon: {
      cn: "+fJJGgBXy.png",
      en: "+JrA8q4lv.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "88",
    game_name: {
      cn: "金喜鹊桥",
      en: "HappyMagpies",
      tw: "金喜鵲橋",
    },
    game_icon: {
      cn: "+nv6RJdjQ.png",
      en: "+yrjLCFLR.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "89",
    game_name: {
      cn: "雷神",
      en: "BigRedWay",
      tw: "雷神",
    },
    game_icon: {
      cn: "+10VPesiE.png",
      en: "+xd4z0bYW.png",
    },
    edited: ["pt-BR", "ja", "es", "cn", "ko", "vn", "th", "en"],
    edited_by: "melo",
    created_at: "2022-02-17T02:33:23-04:00",
    updated_at: "2022-03-15T08:34:07-04:00",
  },
  {
    game_id: "9",
    game_name: {
      cn: "锺馗运财",
      en: "ZhongKui",
      ko: "종규",
      tw: "鍾馗運財",
      vn: "Zhong Kui",
    },
    game_icon: {
      cn: "+sG5uDWK2.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "92",
    game_name: {
      cn: "2018世界杯",
      en: "WorldCupRussia2018",
    },
    game_icon: {
      cn: "+4gcCtvOw.png",
      en: "+yQV8hHsM.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "93",
    game_name: {
      cn: "世界盃明星",
      en: "FootballStar",
    },
    game_icon: {
      cn: "+aiSmIy0p.png",
      en: "+8PK1SvKf.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "94",
    game_name: {
      cn: "世界杯球衣",
      en: "FootballJerseys",
    },
    game_icon: {
      cn: "+Vp1Gh0So.png",
      en: "+9SjJaSCI.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "95",
    game_name: {
      cn: "世界杯球鞋",
      en: "FootballBoots",
    },
    game_icon: {
      cn: "+Gm9VvxVQ.png",
      en: "+U9epZh4q.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "96",
    game_name: {
      cn: "足球宝贝",
      en: "FootballBaby",
    },
    game_icon: {
      cn: "+SDWrnj3O.png",
      en: "+RZ3FJIdT.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "97",
    game_name: {
      cn: "世界杯球场",
      en: "WorldCupField",
    },
    game_icon: {
      cn: "+lGufkcwY.png",
      en: "+KC6lBf1H.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "98",
    game_name: {
      cn: "世界杯全明星",
      en: "All Star Team",
    },
    game_icon: {
      cn: "+NMyzlUGV.png",
      en: "+IuQkljnc.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "99",
    game_name: {
      cn: "跳更高",
      en: "JumpHigher",
      tw: "跳更高",
    },
    game_icon: {
      cn: "+oONBc0x9.png",
      en: "+jbrmZ3l9.png",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "th", "en", "cn"],
    edited_by: "kyrie",
    created_at: "2022-02-16T10:32:13-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "999",
    game_name: {
      "": "",
      cn: "999",
      en: "999",
      th: "test",
      tw: "999",
    },
    game_icon: {
      cn: "+Nfi8adBo.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "aaaaa",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+aUN3bvPg.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "AB1",
    game_name: {
      cn: "皇金漁場2",
      en: "ParadiseII",
    },
    game_icon: {
      cn: "+ON3cysvc.png",
      en: "+LSa8bEQK.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "AB3",
    game_name: {
      cn: "皇金漁場",
      en: "Paradise",
    },
    game_icon: {
      cn: "+4PkyZATO.png",
      en: "+eVSLOOhk.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "AD14",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+dIRlhmyP.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "AT01",
    game_name: {
      cn: "一炮捕鱼",
      en: "OneShotFishing",
    },
    game_icon: {
      cn: "+eJTh0cpQ.png",
      en: "+YIb09tHg.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "AT04",
    game_name: {
      cn: "Thunder",
      en: "Thunder",
    },
    game_icon: {
      cn: "+sIrC116H.png",
      en: "+MsBO0twy.png",
      es: "+MsBO0twy.png",
      id: "+MsBO0twy.png",
      ja: "+MsBO0twy.png",
      ko: "+MsBO0twy.png",
      "pt-BR": "+MsBO0twy.png",
      th: "+MsBO0twy.png",
      vn: "+MsBO0twy.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "BT01",
    game_name: {
      cn: "奪標",
      en: "777",
    },
    game_icon: {
      cn: "+s5Zzormz.png",
      en: "+1XgCG2uL.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "BT02",
    game_name: {
      cn: "抢庄骰子牛牛",
      en: "Banker Dice Bull-Bull",
      tw: "搶莊骰子牛牛",
      vn: "Ngầu Hầm Lắc",
    },
    game_icon: {
      cn: "+S2TnPb0v.png",
      en: "+geK2h8vO.png",
      id: "+geK2h8vO.png",
      ko: "+geK2h8vO.png",
      th: "+geK2h8vO.png",
      vn: "+geK2h8vO.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "CH03",
    game_name: {
      cn: "博丁",
      en: "Pok Deng",
    },
    game_icon: {
      cn: "+xwRvIyev.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-10",
    game_name: {
      cn: "tEST4",
    },
    game_icon: {
      cn: "+jrJCPDl5.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-11",
    game_name: {
      cn: "",
    },
    game_icon: {
      cn: "+l8NDO1ny.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-12",
    game_name: {
      cn: "ahjdgklahsdklgjhasdklgjhasdklgjhaskldg",
      en: "ahjdgklahsdklgjhasdklgjhasdklgjhaskldg",
      ko: "ahjdgklahsdklgjhasdklgjhasdklgjhaskldg",
      th: "ahjdgklahsdklgjhasdklgjhasdklgjhaskldg",
      vn: "ahjdgklahsdklgjhasdklgjhasdklgjhaskldg",
    },
    game_icon: {
      cn: "+hQIqaKXF.jpg",
      en: "+38MFrpI7.jpeg",
      th: "+rflAlwbJ.jpeg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-3",
    game_name: {
      cn: "rita08312",
    },
    game_icon: {
      cn: "+Rnqe5EG0.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-4",
    game_name: {
      cn: "rita0831",
      en: "rita0011",
    },
    game_icon: {
      cn: "+Y9Vf6wj5.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-6",
    game_name: {
      cn: "aaaaaaa",
    },
    game_icon: {
      cn: "+6ULEghxj.jpeg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-7",
    game_name: {
      cn: "TEST",
    },
    game_icon: {
      cn: "+LTnrHEON.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-8",
    game_name: {
      cn: "TEST2",
    },
    game_icon: {
      cn: "+VQSUjmga.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "customize-9",
    game_name: {
      cn: "TEST3",
    },
    game_icon: {
      cn: "+wlqsO0Mf.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "etestset",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+PXp0Sa8Y.png",
      en: "+4v54Orb6.png",
      es: "+4v54Orb6.png",
      id: "+4v54Orb6.png",
      ja: "+4v54Orb6.png",
      ko: "+4v54Orb6.png",
      "pt-BR": "+4v54Orb6.png",
      th: "+4v54Orb6.png",
      vn: "+4v54Orb6.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "fewafwef",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+Zaw6IkPv.jpg",
      en: "+3WPDOIuE.jpg",
      es: "+3WPDOIuE.jpg",
      id: "+3WPDOIuE.jpg",
      ja: "+3WPDOIuE.jpg",
      ko: "+3WPDOIuE.jpg",
      "pt-BR": "+3WPDOIuE.jpg",
      th: "+3WPDOIuE.jpg",
      vn: "+3WPDOIuE.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "GB1",
    game_name: {
      cn: "３２１发射",
      en: "3 2 1 Go!",
    },
    game_icon: {
      cn: "+5GGZEpCk.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "GB2",
    game_name: {
      cn: "怪兽猎人",
      en: "Monster Hunter",
      th: "มอนสเตอร์ ฮันเตอร์",
    },
    game_icon: {
      cn: "+b9ZtBXBE.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "GB6",
    game_name: {
      cn: "富贵小象神",
      en: "Ganesha Jr.",
      th: "พระพิฆเนศน้อย ผู้มั่งคั่ง",
    },
    game_icon: {
      cn: "+S0U6pM72.jpeg",
    },
    edited: ["pt-BR", "ja", "es", "ko", "vn", "id", "th", "en", "cn"],
    edited_by: "rita",
    created_at: "2022-02-25T08:14:22-04:00",
    updated_at: "2022-03-14T07:59:04-04:00",
  },
  {
    game_id: "GO02",
    game_name: {
      cn: "英雄漁機",
      en: "Hero Fish",
    },
    game_icon: {
      cn: "+qSSPY4XX.png",
      en: "+50jx7wgD.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "GO169",
    game_name: {
      cn: "招财龙小钢珠",
      en: "Dragon Pachinko",
    },
    game_icon: {
      cn: "+QrBZgX8T.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "neiltest",
    game_name: {
      cn: "neil-test",
    },
    game_icon: {
      cn: "+WVwoQ2C2.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "test3333",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+BghuSpfE.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "test4444",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+c1dEOyuz.png",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "testest",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+pELfdgvU.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "testsetst",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+GCpwoBfg.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "teststsets",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {
      cn: "+SGFCaa9Z.jpg",
      en: "+FrxZkzYt.jpg",
      es: "+FrxZkzYt.jpg",
      id: "+FrxZkzYt.jpg",
      ja: "+FrxZkzYt.jpg",
      ko: "+FrxZkzYt.jpg",
      "pt-BR": "+FrxZkzYt.jpg",
      th: "+FrxZkzYt.jpg",
      vn: "+FrxZkzYt.jpg",
    },
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
  {
    game_id: "vrbrebbw",
    game_name: {
      cn: "API处尚未建立游戏.",
    },
    game_icon: {},
    edited: [],
    edited_by: "",
    created_at: "",
    updated_at: "",
  },
];

export const adminDataList = [
  {
    id: 1,
    account: "steve",
    dept: "rd",
    avatar_url: "+/jTDvNOza.jpg",
    level: 2,
    edited_by: "steve",
  },
  {
    id: 2,
    account: "winston",
    dept: "rd",
    avatar_url: "+/define.png",
    level: 2,
    edited_by: "steve",
  },
  {
    id: 3,
    account: "gin",
    dept: "rd",
    avatar_url: "+/define.png",
    level: 2,
    edited_by: "steve",
  },
  {
    id: 4,
    account: "kyrie",
    dept: "rd",
    avatar_url: "+/define.png",
    level: 2,
    edited_by: "steve",
  },
  {
    id: 5,
    account: "rita",
    dept: "rd",
    avatar_url: "+/define.png",
    level: 0,
    edited_by: "system",
  },
  {
    id: 6,
    account: "melo",
    dept: "rd",
    avatar_url: "+/define.png",
    level: 2,
    edited_by: "steve",
  },
  {
    id: 7,
    account: "kenny",
    dept: "多媒體",
    avatar_url: "+/define.png",
    level: 0,
    edited_by: "system",
  },
  {
    id: 8,
    account: "larry",
    dept: "rd",
    avatar_url: "+/define.png",
    level: 0,
    edited_by: "system",
  },
  {
    id: 9,
    account: "Neil",
    dept: "rd",
    avatar_url: "+/rqyDeOUn.gif",
    level: 2,
    edited_by: "system",
  },
];

export const record = {
  data: [
    {
      id: 40,
      action: "更改帳號權限(ID:1)",
      parameter: '{"id":1,"level":0,"edited_by":"steve"}',
      edited_by: "steve",
      create_at: "2022-05-11T02:41:34-04:00",
    },
    {
      id: 39,
      action: "新增/修改 helper 資訊(ID:1)",
      parameter:
        '{"game_id":"1","status":true,"lang":"cn","data":[{"content":"\\u003cp\\u003ewww\\u003c/p\\u003e","icon":{"link":false,"name":"無"},"title":"百搭延展特色"},{"content":"","title":"奖励游戏特色"}],"line":"9_2","line_content":{"data":"\\u003cp\\u003e滚轮上由最左至右连续\\u003cspan style=\\"color:#ffff1a;\\"\\u003e2\\u003c/span\\u003e或\\u003cspan style=\\"color:#ffff1a;\\"\\u003e3\\u003c/span\\u003e个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。\\u003c/p\\u003e\\u003cp\\u003e每线取最高赔率为玩家得分。\\u003c/p\\u003e"},"pay_table":{"type":"normal","status":false,"symbol":[]},"version":2,"default_data":[{"content":"\\u003cp\\u003eeee\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"百搭"},{"content":"\\u003cp\\u003efree game test123\\u003c/p\\u003e","icon":{"name":"無","link":false},"title":"分散图奖"}],"game_title":true,"edited_by":"steve"}',
      edited_by: "steve",
      create_at: "2022-04-14T21:43:25-04:00",
    },
    {
      id: 38,
      action: "新增/修改 helper 資訊(ID:204)",
      parameter:
        '{"game_id":"204","status":true,"lang":"cn","data":[{"icon":{"name":"主遊戲特色","link":"main_game_feature"},"title":"主游戏特色","content":"\\u003cp\\u003e盘面上出现任意五个以上的下列图标，即可获得图标上显示的得分。\\u003cbr\\u003e第1~3滚轮上出现任意3个[FREEGAME2]或[FREEGAME4]，即可获得3场免费游戏。\\u003cbr\\u003e当同时符合主游戏和免费游戏特色时，[FREEGAME2]或[FREEGAME4]会做两次计分。\\u003c/p\\u003e"},{"content":"\\u003cp\\u003e滚轮任意位置出现下列图标即得分，每出现1个图标再获得1场免费游戏。\\u003cbr\\u003e滚轮上出现的图标会锁定至免费游戏结束。\\u003cbr\\u003e盘面集满15个图标，可额外获得2000倍的奖励！\\u003cbr\\u003e玩家可多次获得免费游戏，最多场次为15场。\\u003cbr\\u003e免费游戏将结束于场次用完时，或贏得额外满盘奖励时。\\u003cbr\\u003e免费游戏中,投注倍数与触发免费游戏奖励时相同。\\u003cbr\\u003e游戏出现故障时，所有赔付和游戏都视为无效。\\u003c/p\\u003e","icon":{"link":"free_game_feature","name":"免費遊戲特色"},"title":"免费游戏特色"}],"line":"243","line_content":{"data":"\\u003cp\\u003e滚轮上由最左至右连续出现 \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e 个以上相同图标，即可获得该图标的得分奖励。\\u003c/p\\u003e"},"pay_table":{"symbol":[],"status":true,"type":"normal"},"version":1,"default_data":[],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:49:54-04:00",
    },
    {
      id: 37,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":false,"lang":"ph","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"status":true,"type":"normal","symbol":[]},"version":2,"default_data":[],"game_title":false,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:48:25-04:00",
    },
    {
      id: 36,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"pt-BR","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"status":true,"type":"normal","symbol":[]},"version":2,"default_data":[{"content":"\\u003cp\\u003e[WW] substitui todos os símbolos, exceto [SF].\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"SELVAGEM"},{"content":"\\u003cp\\u003e3, 4 ou 5 [SC] em qualquer lugar dos molinetes ganham uma aposta total de 2X, 10X ou 100X.\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"DESORDEM","titleType2":"DESORDEM"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:48:20-04:00",
    },
    {
      id: 35,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"ja","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"type":"normal","symbol":[],"status":true},"version":2,"default_data":[{"content":"\\u003cp\\u003e[WW]は[SF]以外のすべての絵柄の代わりになります。\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"ワイルド"},{"content":"\\u003cp\\u003eリール上のどこかに[SC]が3、4、5個止まると、総ベットポイントの2倍、10倍、100倍のポイントが手に入ります。\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"分散絵柄","titleType2":"分散絵柄"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:48:15-04:00",
    },
    {
      id: 34,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"es","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"symbol":[],"status":true,"type":"normal"},"version":2,"default_data":[{"content":"\\u003cp\\u003e[W] sustituye a cualquier símbolo, excepto [SF].\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"COMODÍN"},{"content":"\\u003cp\\u003e3, 4 o 5 [SC] en cualquier parte de los rodillos ganará 2x, 10x o 100x apuesta total.\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"DISPERSIÓN","titleType2":"DISPERSIÓN"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:48:09-04:00",
    },
    {
      id: 33,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"ko","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003e플레이어는 맨 왼쪽부터 오른쪽까지의 연속 릴에서 같은 심볼이 \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e 번 이상 나타나면 상품을 획득합니다.\\u003c/p\\u003e"},"pay_table":{"status":true,"type":"normal","symbol":[]},"version":2,"default_data":[{"icon":{"link":"W","name":"百搭"},"title":"WILD","content":"\\u003cp\\u003e[WW]는 [SF]를 제외한 모든 심벌을 대체합니다.\\u003c/p\\u003e"},{"content":"\\u003cp\\u003e릴 어디에서든 3, 4 또는 5 [SC]가 나타나면 총 배팅액의 2배, 10배, 100배를 획득합니다.\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"SCATTER","titleType2":"SCATTER"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:48:04-04:00",
    },
    {
      id: 32,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"vn","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"symbol":[],"status":true,"type":"normal"},"version":2,"default_data":[{"content":"\\u003cp\\u003e[WW] thay thế cho tất cả các biểu tượng ngoại trừ [SF].\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"WILD"},{"titleType2":"SCATTER","content":"\\u003cp\\u003e3, 4, 5 hình [SC] ở bất kỳ vị trí nào trên các guồng quay sẽ thắng tổng cược gấp 2, 10 hoặc 100 lần.\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"SCATTER"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:47:58-04:00",
    },
    {
      id: 31,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"id","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"status":true,"type":"normal","symbol":[]},"version":2,"default_data":[{"content":"\\u003cp\\u003e[WW] menggantikan semua simbol kecuali [SF].\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"WILD"},{"content":"\\u003cp\\u003e3, 4 atau 5 [SC] di manapun pada gulungan memberikan 2X, 10X atau 100X taruhan total.\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"SCATTER","titleType2":"SCATTER"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:47:52-04:00",
    },
    {
      id: 30,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"th","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003eผู้เล่นจะชนะรางวัลโดยมีสัญลักษณ์เดียวกัน \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e ตัวหรือมากกว่าปรากฎบนวงล้อต่อเนื่องจากซ้ายไปขวา.\\u003c/p\\u003e"},"pay_table":{"status":true,"type":"normal","symbol":[]},"version":2,"default_data":[{"content":"\\u003cp\\u003e[W] ทดแทนได้ทุกสัญลักษณ์ยกเว้น [F]\\u003c/p\\u003e","icon":{"name":"百搭","link":"W"},"title":"ไวลด์"},{"titleType2":"สแคตเตอร์","content":"\\u003cp\\u003e\\"หากสัญลักษณ์ [SC] 3, 4 หรือ 5 ตัว ปรากฏที่ใดก็ได้บนวงล้อ\\u0026nbsp;\\u003cbr\\u003eจะชนะ 2X, 10X หรือ 100X ของการเดิมพันทั้งหมด\\"\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"สแคตเตอร์"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:47:46-04:00",
    },
    {
      id: 29,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"en","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003ePlayer will win prize with any \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e or more the same symbols appearing on the continuous reels from leftmost to right.\\u003c/p\\u003e"},"pay_table":{"status":true,"type":"normal","symbol":[]},"version":2,"default_data":[{"icon":{"link":"W","name":"百搭"},"title":"WILD","content":"\\u003cp\\u003e\\u0026nbsp;[W] substitutes for all symbols except [SC].\\u003c/p\\u003e"},{"titleType2":"SCATTER","content":"\\u003cp\\u003e3, 4 or 5 [SC] anywhere on reels win 2X, 10X or 100X total bet.\\u003c/p\\u003e","icon":{"name":"免費遊戲 / 分散圖獎","link":"F"},"title":"SCATTER"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:47:40-04:00",
    },
    {
      id: 28,
      action: "新增/修改 helper 資訊(ID:187)",
      parameter:
        '{"game_id":"187","status":true,"lang":"cn","data":[],"line":"243","line_content":{"data":"\\u003cp\\u003e滚轮上由最左至右连续出现 \\u003cspan style=\'color:#ffff1a\'\\u003e3\\u003c/span\\u003e 个以上相同图标，即可获得该图标的得分奖励。\\u003c/p\\u003e"},"pay_table":{"type":"normal","symbol":[],"status":true},"version":1,"default_data":[{"content":"\\u003cp\\u003e[W]可替代除了[SC]以外的任意图标来得到连线分数。\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"百搭"},{"icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"分散图奖","titleType2":"分散图奖","content":"\\u003cp\\u003e滚轮上任意位置出现3、4或5个[SC]，可获得2X、10X或100X总押注得分。\\u003c/p\\u003e"}],"game_title":true,"edited_by":"rita"}',
      edited_by: "rita",
      create_at: "2022-04-13T21:47:31-04:00",
    },
    {
      id: 27,
      action: "新增/修改 helper 資訊(ID:1)",
      parameter:
        '{"game_id":"1","status":true,"lang":"cn","data":[{"content":"\\u003cp\\u003ewww\\u003c/p\\u003e","icon":{"link":false,"name":"無"},"title":"百搭延展特色"},{"content":"","title":"奖励游戏特色"}],"line":"108","line_content":{"data":"\\u003cp\\u003e滚轮上由最左至右连续出现 \\u003cspan style=\\"color:#ffff1a;\\"\\u003e3\\u003c/span\\u003e 个以上相同图标，即可获得该图标的得分奖励。\\u003c/p\\u003e"},"pay_table":{"status":false,"symbol":[],"type":"normal"},"version":1,"default_data":[{"content":"\\u003cp\\u003eeee\\u003c/p\\u003e","icon":{"link":"W","name":"百搭"},"title":"百搭"},{"title":"分散图奖","content":"\\u003cp\\u003efree game test123\\u003c/p\\u003e","icon":{"name":"無","link":false}}],"game_title":true,"edited_by":"steve"}',
      edited_by: "steve",
      create_at: "2022-04-13T21:18:48-04:00",
    },
    {
      id: 26,
      action: "新增/修改 helper 資訊(ID:1)",
      parameter:
        '{"game_id":"1","status":true,"lang":"cn","data":[{"content":"\\u003cp\\u003eascascasca\\u003c/p\\u003e","title":"免费游戏特色"},{"content":"","icon":{"link":false,"name":"無"},"title":"奖励游戏特色"},{"content":"\\u003cp\\u003easaㄇs\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"+"}],"line":"88","line_content":{"data":"\\u003cp\\u003e滚轮上由最左至右连续3个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。\\u003c/p\\u003e\\u003cp\\u003e每线取最高赔率为玩家得分。\\u003c/p\\u003e\\u003cp\\u003e游戏出现故障时，所有赔付和游戏都视为无效。\\u003c/p\\u003e"},"pay_table":{"type":"normal","status":true,"symbol":["w","wwww"]},"version":4,"default_data":[{"content":"\\u003cp\\u003ea\\u003c/p\\u003e\\u003cp\\u003e#abc\\u003c/p\\u003e\\u003cp\\u003e#efg\\u003c/p\\u003e","icon":{"link":"F","name":"免費遊戲 / 分散圖獎"},"title":"TEST"},{"content":"\\u003cp\\u003edd\\u003c/p\\u003e","title":"奖励游戏特色YYY"}],"game_title":true,"edited_by":"steve"}',
      edited_by: "steve",
      create_at: "2022-04-13T01:55:05-04:00",
    },
  ],
  total_count: 40,
};

export const helpDetailData = {
  data: [
    {
      content: "<p>www</p>",
      icon: {
        link: false,
        name: "無",
      },
      title: "百搭延展特色",
    },
    {
      content: "",
      title: "奖励游戏特色",
    },
  ],
  default_data: [
    {
      content: "<p>eee</p>",
      icon: {
        link: "W",
        name: "百搭",
      },
      title: "百搭",
    },
    {
      content: "<p>free game test123</p>",
      icon: {
        link: false,
        name: "無",
      },
      title: "分散图奖",
    },
  ],
  lang: "cn",
  status: true,
  game_title: true,
  line: "9_2",
  line_content: {
    data: '<p>滚轮上由最左至右连续<span style="color:#ffff1a;">2</span>或<span style="color:#ffff1a;">3</span>个以上的相同图标出现在押注线上，即可获得该图标的得分奖励。</p><p>每线取最高赔率为玩家得分。</p>',
  },
  pay_table: {
    status: false,
    symbol: [],
    type: "normal",
  },
  version: 2,
  edited_by: "steve",
  created_at: "2022-02-11T11:57:58-04:00",
  updated_at: "2022-04-14T21:43:25-04:00",
};
